Improve MHD stability further
gamer-project/gamer pull request #151
Opened 2022-10-26 02:09 UTC by hyschive

This is a follow-up PR of #149 to improve the stability of MHD simulations further. It adds the following features.

### Major updates
- Apply iterative interpolation (i.e., `MONO_MAX_ITER`) *only on failed cells*.
  - Necessary for all patches to see exactly the same B field near the coarse-fine boundaries.
  - Controlled by the option `INTERP_MASK` in `Macro.h`. Enable it by default.
- Switch to a different Riemann solver **directly in the fluid solver** if the default one fails.
  - Controlled by the option `RSOLVER_RESCUE` in `CUFLU.h`.
- Support `AUTO_REDUCE_MINMOD_*` and `AUTO_REDUCE_INT_MONO_*` to automatically reduce `MINMOD_COEFF` and `INT_MONO_COEFF(_B)` when the fluid solver fails.
  - Used together with `AUTO_REDUCEDT`.
  - `AUTO_REDUCE_MINMOD_*` can be used to replace `MINMOD_MAX_ITER`. The latter is not recommended for MHD simulations since it only applies to patch groups containing failed cells, which will break the B field consistency between nearby patches.
  - MHD simulations prefer `INT_MONO_COEFF_B <= 1.5` for stability.

### Minor updates
- Support `OPT__CK_INPUT_FLUID` to validate the input data of the fluid solver.
- Separate `INT_MONO_COEFF` and `INT_MONO_COEFF_B`; the latter is for B field.

2022-10-30 17:12 UTC, hfhsieh requested changes
Look goods. I have additional comments:

- [ ] In `ClusterMerger/Input__Parameter`, the new runtime parameters `AUTO_REDUCE_MINMOD_*` and `AUTO_REDUCE_INT_MONO_*` are not added.
- [ ] In `CUFLU.h` there is additional setting for certain `RSOLVER` (e.g., `EULERY`). It seems that we should also enable them for `RSOVLER_RESCUE`. However, there could be conflicts between `RSOVLER` and `RSOVLER_RESCUE`, such as `RSOVLER = HLLE / HLLC / HLLD` and `RSOVLER_RESCUE = ROE`. Maybe we should also limit the allowed value of `RSOVLER_RESCUE` based on `RSOVLER`
- [ ] Also check `RSOVLER_RESCUE` in `Aux_Check_Parameter()` as `RSOLVER`. For example, if `EOS != EOS_GAMMA`, `RSOVLER_RESCUE` can not be set to either `ROE`  or `EXACT`

2022-11-01 03:57 UTC, hyschive commented on src/Interpolation/Interpolate.cpp
> +            Aux_Error( ERROR_INFO, "INT_VANLEER/INT_MINMOD3D/INT_MINMOD1D do not support MONO_MAX_ITER != 0 !!\n" );
Done. But I still keep the check here in case `Interpolate_Iterate()` is used in other places.

2022-11-01 04:00 UTC, hyschive commented on src/Interpolation/Interpolate.cpp
>                 }
But they are printed in separate lines.

2022-11-01 04:07 UTC, hyschive commented on src/Interpolation/Interpolate.cpp
> +         Fail_AnyCell |= Fail_ThisCell;
No. We must update `Fail_AnyCell` within the `for (int i=0; i<FSize3D; i++)` loop. In addition, I think it's conceptually clearer to associate it with `5. check unphysical results`.

2022-11-01 04:14 UTC, hyschive commented on src/Model_Hydro/CPU_Hydro/CPU_FluidSolver_MHM.cpp
> +#              if   ( RSOLVER == EXACT  &&  !defined MHD )
Thanks for catching this stupid bug! This fix may improve the stability further.

2022-11-01 08:38 UTC, hfhsieh commented on src/Interpolation/Interpolate.cpp
> +            Aux_Error( ERROR_INFO, "INT_VANLEER/INT_MINMOD3D/INT_MINMOD1D do not support MONO_MAX_ITER != 0 !!\n" );
Got it.

2022-11-01 08:38 UTC, hfhsieh commented on src/Interpolation/Interpolate.cpp
>                 }
I see, then ignore this comment.

2022-11-01 08:40 UTC, hfhsieh commented on src/Interpolation/Interpolate.cpp
> +         Fail_AnyCell |= Fail_ThisCell;
True, I misread the code.

2022-11-01 08:41 UTC, hfhsieh approved these changes

2022-11-01 08:57 UTC, merged