Makefile configuration
gamer-project/gamer pull request #186
Opened 2023-04-07 08:02 UTC by ChunYen-Chen

To change the Makefile more easily and easy to generate, we now use the configure.py to generate the Makefile.
Here are some features:
1. Auto check the conflict simulation option.
2. Auto check the conflict of parallelization option.
3. The library paths and the compilation flags are given by a certain config file.

2023-04-10 08:07 UTC, KunkelAlexander approved these changes
I think the Makefile generator is really helpful and works well. The code works fine with Python 3.8. I tested it on Eureka with the Hydro tests and on the lab computer in ELBDM mode. Typos and wrong file paths are handled correctly. It is easy to add new config files and new Makefile options. I am only a little unhappy with step 1 d) when adding new Makefile options because there is some redundant code. This step checks whether different options are compatible with one another (Do we need `COMOVING` in `HYDRO` etc.). But then again, I do not think simplifying the script further is worth spending much time on.

2023-04-10 10:01 UTC, ChunYen-Chen commented
About the step 1 d) in the developer guide, I am looking for the solution. It seems that the `subargparse` might be able to minimize the code, but I am still trying. I will let you know if it works.

2023-04-11 08:34 UTC, ChunYen-Chen commented
Eventually, I did not use `subargparse` since it does not work well of the custom help message.
@KunkelAlexander Can you help me ot review the simplified code? Thanks!

2023-04-11 08:36 UTC, KunkelAlexander commented
@ChunYen-Chen

2023-04-11 12:46 UTC, ChunYen-Chen commented
@KunkelAlexander Yes, this is exactly what I want. Thank you!

2023-04-12 07:49 UTC, ChunYen-Chen commented
@hyschive I think the script is ready for you to review. Thanks!

2023-04-13 11:50 UTC, ChunYen-Chen commented
@hyschive I have add a simple makefile generate script of acoustic wave test under `example`.

2023-04-27 02:09 UTC, hyschive commented
@ChunYen-Chen Could you update this PR as suggested below? Thanks!
- Merge the latest `main` branch
- Support the new compilation option [LIBYT_INTERACTIVE](https://github.com/gamer-project/gamer/blob/main/src/Makefile#L234)

2023-04-28 03:06 UTC, ChunYen-Chen commented
@hyschive Besides `LIBTY_INTERACTIVE`, I also add `FEEDBACK` to the configure file.

2023-04-30 07:54 UTC, ChunYen-Chen commented
@hyschive I have added the modified option `SUPPORT_FFTW` to the latest commit.

2023-05-30 05:13 UTC, ChunYen-Chen commented
@hyschive I also add the changing `Input__*` file script to this PR.

2023-06-08 13:41 UTC, hyschive requested changes
@ChunYen-Chen Great work! It's super useful. I only have two major comments:
- [x] Integrate each `A.config` and `A.make` pair and then remove `*.make`. It's because (i) `*PATH` and `*FLAG` are usually tightly related to each other and (ii) it's quite normal for different systems to adopt different `*FLAG` even with the same compiler. It will also simplify the procedure of adding a new system.
  - [x] Relatedly, you can separate `example.config` into `example_intel.config, example_gnu.config` and `eureka.config` into `eureka_intel.config, eureka_gnu.config`.
  - [x] Remove the option `--flag`.
  - [x] Check other related comments in `configure.py`.
- [x] Set both serial compiler (`CXX`) and MPI compiler (`CXX_MPI`) in `*.config` and then remove `serial_compiler` from `configure.py`.

Other general comments:
- [x] Remove `NAOC_laohu.config, UIUC_1.config, UIUC_2.config, NCSA_*.config` (also remove them from `Makefile`).
- [x] Rename `NASA_Pleiades.config` as `pleiades.config`, `NCTS.config` as `ncts.config`, and `NTHU_fomalhaut.config` as `fomalhaut.config` for consistency.
- [x] Add `src/generate_make.sh` to `.gitignore`.
- [x] Set default values for all boolean options (e.g., `GRAVITY`: off, `CONSERVE_MASS`: on).

2023-06-08 13:41 UTC, hyschive commented on src/configure.py
> +            print("%-20s : %r"%(name, val))
- [ ] How about also printing options that are disabled? For example,
```
        if val: opt_str += "-D%s "%(name)
        print("%-20s : %r"%(name, val))
```
- [ ] Increase `20` to `25` (modify the lines below too).

2023-06-09 01:37 UTC, hyschive commented on src/configure.py
> +parser.add_argument( "--unsplit_gravity",
@ChunYen-Chen For all options with defaults depending on other options, we need to do that in a separate routine _after_ loading all arguments. It's similar to [Init_ResetParameter()](https://github.com/gamer-project/gamer/blob/main/src/Init/Init_ResetParameter.cpp) in gamer.

2023-06-09 02:35 UTC, ChunYen-Chen commented on configs/eureka.config
> +FFTW3_PATH      /software/fftw/3.3.10-intel-2022.0.1-openmpi-4.1.1-ucx_mt
Which path do you want, `FFTW2_PATH` or `FFTW3_PATH`?

2023-06-09 02:40 UTC, hyschive commented on configs/eureka.config
> +FFTW3_PATH      /software/fftw/3.3.10-intel-2022.0.1-openmpi-4.1.1-ucx_mt
`FFTW3_PATH` (which corresponds to `default3` instead of `default`).

2023-06-09 03:58 UTC, ChunYen-Chen commented on src/configure.py
> +        color_print("Warning: %s already exist and will be overwriten."%(GAMER_MAKE_OUT), BCOLOR.WARNING)
Updated!

2023-06-09 03:58 UTC, ChunYen-Chen commented on src/configure.py
> +    Use the `-h` or `--help` to get the short help message. Use `-lh` to get detail help message.
Updated!

2023-06-09 03:58 UTC, ChunYen-Chen commented on src/configure.py
> +# The convert name from the python argument to the makefile argument.
Updated!

2023-06-09 03:59 UTC, ChunYen-Chen commented on src/configure.py
> +parser.add_argument( "--passive", type=int, metavar="NUMBER",
Updated!

2023-06-09 03:59 UTC, ChunYen-Chen commented on src/configure.py
> +parser.add_argument( "--par_attribute", type=int, metavar="NUMBER",
Updated!

2023-06-09 03:59 UTC, ChunYen-Chen commented on src/configure.py
> +    if not success: raise BaseException(BCOLOR.FAIL+"The above validations are fail."+BCOLOR.ENDC)
Updated!

2023-06-09 03:59 UTC, ChunYen-Chen commented on src/configure.py
> +  This code can be separated to the 5 parts which are `Packages`, `Global variables`, `Classes`, `Functions`, and
Updated!

2023-06-09 04:03 UTC, ChunYen-Chen commented on src/configure.py
> +GAMER_DESCRIPTION = "Prepare customize Makefile for GAMER.\nThe default value starts with '*' sign.\nTo show the detail help message, please use -lh argument."
Updated!

2023-06-09 04:04 UTC, ChunYen-Chen commented on src/configure.py
> +    After the command finishes, the `Makefile` will be generated.
Updated!

2023-06-09 04:04 UTC, ChunYen-Chen commented on src/configure.py
> +  1. Add new simulation option:
Updated!

2023-06-09 04:05 UTC, ChunYen-Chen commented on src/configure.py
> +    a. The string will be replaced by this script need to be sandwitched by `@@@`.
Updated!

2023-06-09 04:05 UTC, ChunYen-Chen commented on src/configure.py
> +       (You can find it in the `Global variable` part of the code.)
Updated!

2023-06-09 04:05 UTC, ChunYen-Chen commented on src/configure.py
> +    b. Add the python argument reader for the new simulation option in the `Main execution` part of the code.
Updated!

2023-06-09 04:05 UTC, ChunYen-Chen commented on src/configure.py
> +    a. Add a new line in the Makefile_base in the path section.
Updated!

2023-06-09 04:06 UTC, ChunYen-Chen commented on src/configure.py
> +    b. Add a new line in the path config file.
Updated!

2023-06-09 04:06 UTC, ChunYen-Chen commented on src/configure.py
> +    a. Add a new line in the Makefile_base in the flag section.
Updated!

2023-06-09 04:06 UTC, ChunYen-Chen commented on src/configure.py
> +    b. Add a new flag key `["NEW_FLAG":""]` in `flags` of `load_compile()`.
Yes! Updated!

2023-06-09 04:06 UTC, ChunYen-Chen commented on src/configure.py
> +    c. Add a new line in the path config file.
Updated!

2023-06-09 04:07 UTC, ChunYen-Chen commented on src/configure.py
> +# detail help message
Updated!

2023-06-09 04:07 UTC, ChunYen-Chen commented on src/configure.py
> +# 1.1 print out the detail help message then exit
Updated!

2023-06-09 04:07 UTC, ChunYen-Chen commented on src/configure.py
> +# 2.2 Check if the argument are valid
Updated!

2023-06-09 04:07 UTC, ChunYen-Chen commented on src/configure.py
> +    a. `print_help`: Showing the essential message only. The default option should start with '*' sign.
Updated!

2023-06-09 04:08 UTC, ChunYen-Chen commented on src/configure.py
> +    # NOTE: every -Doption must have trailing space
Updated!

2023-06-09 04:08 UTC, ChunYen-Chen commented on src/configure.py
> +    UNDERLINE = '\033[4m'
Updated!

2023-06-09 04:08 UTC, ChunYen-Chen commented on src/configure.py
> +        opt_str = add_option( opt_str, "SERIAL", True )  # hard coded the option of serial
Updated!

2023-06-09 04:08 UTC, ChunYen-Chen commented on src/configure.py
> +                     help="Enable magnetohydrodynamic.\n"
Updated!

2023-06-09 04:08 UTC, ChunYen-Chen commented on src/configure.py
> +                     help="Whether or not the --eos set is barotropic.\n"
Updated!

2023-06-09 04:08 UTC, ChunYen-Chen commented on src/configure.py
> +                   )
Updated!

2023-06-09 04:09 UTC, ChunYen-Chen commented on src/configure.py
> +                     help="Store the potential ghost-zone for each patch on each side.\n"
Updated!

2023-06-09 04:09 UTC, ChunYen-Chen commented on src/configure.py
> +                     help="Comoving frame for cosmological simulation.\n"
Updated!

2023-06-09 04:09 UTC, ChunYen-Chen commented on src/configure.py
> +                     help="Enable particle.\n"
Updated!

2023-06-09 04:09 UTC, ChunYen-Chen commented on src/configure.py
> +                     help="Feedback from particles to grids.\n"
Updated!

2023-06-09 04:10 UTC, ChunYen-Chen commented on src/configure.py
> +                     help="Set the number of user defined particle attributes.\n"
Updated!

2023-06-09 04:10 UTC, ChunYen-Chen commented on src/configure.py
> +                     help="Set the maximum level of AMR.\n"
Updated!

2023-06-09 04:10 UTC, ChunYen-Chen commented on src/configure.py
> +                     help="Set the maximum patchs on each level of AMR.\n"
Updated!

2023-06-09 04:10 UTC, ChunYen-Chen commented on src/configure.py
> +                     help="Set size of each direction of a single patch.\n"
Updated!

2023-06-09 04:10 UTC, ChunYen-Chen commented on src/configure.py
> +                     help="Enable to measure timing.\n"
Updated!

2023-06-09 04:11 UTC, ChunYen-Chen commented on src/configure.py
> +                     help="Enable to measure GPU time.\n"
Updated!

2023-06-09 04:11 UTC, ChunYen-Chen commented on src/configure.py
> +                     help="Support HDF5 format.\n"
Updated!

2023-06-09 04:11 UTC, ChunYen-Chen commented on src/configure.py
> +                     help="Use patch group as the unit in libyt. Note that this will speed up inline-analysis but increase memory consumption.\n"
Updated!

2023-06-09 04:11 UTC, ChunYen-Chen commented on src/configure.py
> +                     help="This activates python prompt and does not shut down a simulation when there are errors in an inline python script\n"
Updated!

2023-06-09 04:12 UTC, ChunYen-Chen commented on src/configure.py
> +NAME_TABLE        = {"model":"MODEL", "passive":"NCOMP_PASSIVE_USER", "flu_scheme":"FLU_SCHEME",
Updated!

2023-06-09 04:12 UTC, ChunYen-Chen commented on src/configure.py
> +    Calculate the distance of two string.
Updated!

2023-06-09 04:12 UTC, ChunYen-Chen commented on src/configure.py
> +                msg += 'unrecognized arguments: %s, do you mean: %s ?\n'%(arg, pos_key)
Updated!

2023-06-09 04:12 UTC, ChunYen-Chen commented on src/configure.py
> +                color_print("MHD only supports EXACT, ROE, HLLE, and HLLD Riemann solver.", BCOLOR.FAIL)
Updated!

2023-06-09 04:13 UTC, ChunYen-Chen commented on src/configure.py
> +                color_print("Pure hydro only supports EXACT, ROE, HLLE, and HLLC Riemann solver.", BCOLOR.FAIL)
Updated!

2023-06-09 04:13 UTC, ChunYen-Chen commented on src/configure.py
> +                color_print("RTVD and CTU are only supported for --eos=GAMMA.", BCOLOR.FAIL)
Updated!

2023-06-09 04:13 UTC, ChunYen-Chen commented on src/configure.py
> +                color_print("--gravity must be enabled when --self_interaction.", BCOLOR.FAIL)
Updated!

2023-06-09 04:14 UTC, ChunYen-Chen commented on src/configure.py
> +            color_print("One of --gravity or --tracer must be enabled for --particle.", BCOLOR.FAIL)
Updated!

2023-06-09 04:14 UTC, ChunYen-Chen commented on src/configure.py
> +        color_print("--timing_solver must enable --timing.", BCOLOR.FAIL)
Updated!

2023-06-09 04:14 UTC, ChunYen-Chen commented on src/configure.py
> +            color_print("--overlap_mpi must enable --mpi.", BCOLOR.FAIL)
Updated!

2023-06-09 04:14 UTC, ChunYen-Chen commented on src/configure.py
> +        color_print("Warning: Riemann solver is useless for RTVD.", BCOLOR.WARNING)
Updated!

2023-06-09 04:14 UTC, ChunYen-Chen commented on src/configure.py
> +PARTICALE_OPTION     = ["particle", "par_attribute", "tracer", "store_acc", "feedback", "star_formation"]
Updated!

2023-06-09 04:18 UTC, ChunYen-Chen commented on tool/simulation/change_parameters.py
Done!

2023-06-09 04:19 UTC, ChunYen-Chen commented on configs/example.make
> +# To comment in this file, start with "#" in the begining of the line.
Updated!

2023-06-09 04:20 UTC, ChunYen-Chen commented on src/configure.py
> +                     help="Select the archtecture of GPU.\n"
Updated!

2023-06-09 05:04 UTC, ChunYen-Chen commented on src/configure.py
> +    def parse_args(self, args=None, namespace=None):
Fixed. Now the script will print out the unrecognized positional argument. 

`min_dist` is actually a variable to store the minimum distant of all `NAME_TABLE`. I add a new variable called `close_dist` to approach what you like.

2023-06-09 05:09 UTC, ChunYen-Chen commented on src/configure.py
> +    a. Make sure you have added the necessary source files in `Makefile_base`.
Updated!

2023-06-09 05:09 UTC, ChunYen-Chen commented on src/configure.py
> +    f. [Optional] Add the warning rules in `warning()`. (You can find it in the `Functions` part of the code.)
Updated!

2023-06-09 07:20 UTC, ChunYen-Chen commented on src/configure.py
> +    validation then store the parameter
The `load_sim()` was a part of the function. I will change the comment.

2023-06-09 08:14 UTC, ChunYen-Chen commented on src/configure.py
> +ELBDM_OPTION         = ["model", "passive", "conserve_mass", "laplacian_four", "self_interaction"]
Those options are in `psidm` branch only. I don't think I should add them in this PR.

2023-06-09 09:12 UTC, ChunYen-Chen commented on configs/example.make
> +CXXFLAG -flag3
Yes, it does.

2023-06-09 09:58 UTC, ChunYen-Chen commented on src/configure.py
> +        temp = list( filter( None, re.split(" |:=|\n", line) ) )
I use `re.split` to spilt the string with ` ` and `:=`, and the reason I use `filter` is that the `re.split` will give me empty element which I don't want.

2023-06-09 10:01 UTC, ChunYen-Chen commented on src/configure.py
> +           color_print( "WARNING: %s is not set."%temp[0], BCOLOR.WARNING )
Yeap, I actually do that in `warning()`. I guess I just remove this line for good.

2023-06-14 02:39 UTC, hyschive commented
@ChunYen-Chen When enabling `GAMER_DEBUG`, can you turn on `BITWISE_REPRODUCIBILITY` automatically unless it's explicitly disabled by `--bitwise-reproducibility=False`?

2023-06-14 11:02 UTC, ChunYen-Chen commented on src/configure.py
About the autocomplete argument, that is actually a feature fo `argparse`. If you do not like that feature, it can only be removed in Python3.

2023-06-14 11:06 UTC, ChunYen-Chen commented on src/configure.py
> +                color_print("MHD only supports MHM_RP and CTU.", BCOLOR.FAIL)
I change the output format in the next commit, please let me know if you want to change it further.

2023-06-14 12:05 UTC, ChunYen-Chen commented
@hyschive @KunkelAlexander I have changed the files accordingly. Here are some major changing.
1. You have to assign the boolean when using `--argument`. e.g. `--double=True`.
2. Adding a new argument is more convinent now.
3. `*.config` file now contains flags, compilers, and paths.
4. We use the `depend` in `parse.add_argument()` to specify the argument which depend on other argument.
Thanks in advance for the reviewing!

2023-06-15 05:36 UTC, ChunYen-Chen commented on src/configure.py
https://docs.python.org/3.5/library/argparse.html#allow-abbrev

2023-06-15 08:28 UTC, ChunYen-Chen commented
I add the `allow_abbrev=False` for script running under python version `>=3.5`. Please let me know if you would like to keep this feature or not.

2023-06-16 10:06 UTC, hyschive reviewed
@ChunYen-Chen This version is even better than the previous one. Good job! I think it is ready for merging and I've added some final minor comments.

Please check typos again carefully.

2023-06-17 04:05 UTC, ChunYen-Chen commented on configs/pleiades.config
> +CXX_MPI /bin/cc
It was just a typo.

2023-06-17 04:14 UTC, ChunYen-Chen commented on src/configure.py
> +                         constrain={ True:{"dual":[NONE_STR, "DE_EINT"]} },
Actually, it does not right now.

2023-06-17 05:03 UTC, ChunYen-Chen commented on src/configure.py
> +    def parse_args(self, args=None, namespace=None):
Yes, the bug is fixed now.

2023-06-17 05:06 UTC, ChunYen-Chen commented on src/configure.py
> +    args, sim_names, depends, constrains = parser.parse_args()
It is actually the previous `NAME_TABLE` variable mapping to GAMER simulation options.

2023-06-17 05:07 UTC, ChunYen-Chen commented on src/configure.py
> +    args, sim_names, depends, constrains = parser.parse_args()
Or I just called it `name_table`?

2023-06-17 05:21 UTC, ChunYen-Chen commented on src/configure.py
> +               paths[temp[0]] = ''
Yes, we should! Thanks for pointing out.

2023-06-17 05:29 UTC, ChunYen-Chen commented on src/configure.py
> +    c. [Optional] If the argument depends on another option, please add `depend={"depend_arg":depend_value}`
Yes!

2023-06-17 05:30 UTC, ChunYen-Chen commented on configs/eureka.config
NP!

2023-06-17 05:40 UTC, ChunYen-Chen commented
@hyschive I have updated the files accordingly.

2023-06-17 08:32 UTC, hyschive reviewed
@ChunYen-Chen Just a few final comments!

2023-06-17 08:32 UTC, hyschive commented on src/configure.py
> +                         help="The dual-energy formalism (DE_ENPY: entropy, DE_EINT: internal energy). DE_EINT is not supported yet. Useless for RTVD.\n\n"
Remove the extra "\n"

2023-06-17 08:32 UTC, hyschive commented on src/configure.py
> +# 2.1 Load the machine setup
Typo above this line: makiefile

2023-06-17 08:32 UTC, hyschive commented on src/configure.py
> +    if num == 0: raise BaseException("The string @@@%s@@@ is not replaced correctlly."%key)
Typo: correctlly.

Fix the following lines too.

2023-06-17 08:32 UTC, hyschive commented on configs/eureka_intel.config
> +CXXFLAG -g
Remove the trailing space.

2023-06-17 08:32 UTC, hyschive commented on src/configure.py
> +    # 2. Conditionlly default argument.
This change hasn't been applied yet.

2023-06-17 08:32 UTC, hyschive commented on src/configure.py
> +                                     False:{"flux":["ROE", "HLLE", "HLLC"]} },
I thought we should remove `EXACT` from the `True` list and add it back to the `False` list.

2023-06-17 11:02 UTC, hyschive approved these changes

2023-06-17 11:02 UTC, merged