FFTW startup runtime option
gamer-project/gamer pull request #198
Opened 2023-05-08 10:40 UTC by KunkelAlexander

This pull request introduces the runtime option  `OPT__FFTW_STARTUP` that determines whether to use `FFTW_ESTIMATE`, `FFTW_MEASURE` or `FFTW_PATIENT` as default for the FFTW plans used in GAMER. 
The corresponding option can be set in `Input__Parameter` via  `OPT__FFTW_STARTUP = 0/1/2` (estimate, measure, patient (only FFTW3).

2023-05-08 10:42 UTC, KunkelAlexander commented
@hyschive 
I also renamed the fftw3 single and double omp options to make the naming consistent with the rest of gamer. 
In addition, I also added three lines of code that read an MHD related option back from the hdf5 file. I think that someone just forgot to read the parameter back in because it is stored in the hdf5 file properly. If you do not want to meddle with this option, I can delete the corresponding lines of code.

2023-05-09 01:15 UTC, KunkelAlexander commented
@hyschive 
This pull request is ready for review.

2023-05-09 01:51 UTC, hyschive requested changes
@KunkelAlexander Thanks for adding this new feature! I've left some inline comments.

2023-05-09 01:51 UTC, hyschive commented on src/Output/Output_DumpData_Total_HDF5.cpp
> +//                2466 : 2023/05/08 --> output OPT__FFTW_STARTUP
Search the keyword `FormatVersion` in this file and update it too.

2023-05-09 01:51 UTC, hyschive commented on src/Output/Output_DumpData_Total_HDF5.cpp
> +   InputPara.Opt__FFTW_Startup       = OPT__FFTW_STARTUP;
You need to call `H5Tinsert()` to insert this new parameter. Check `Opt__InitBFieldByFile` as an example.

2023-05-09 02:27 UTC, KunkelAlexander commented on src/Main/Main.cpp
> +bool                 FFTW3_DOUBLE_OMP_ENABLED, FFTW3_SINGLE_OMP_ENABLED;
That means I should change it back? No problem. :)

2023-05-09 02:29 UTC, KunkelAlexander commented on include/Macro.h
> +#define FFTW_STARTUP_PATIENT  2
Done!

2023-05-09 02:34 UTC, KunkelAlexander commented on src/Init/Init_Load_Parameter.cpp
> +   ReadPara->Add( "OPT__FFTW_STARTUP",          &OPT__FFTW_STARTUP,              -1,               0,             NoMax_int      );
I agree and changed the code accordingly.

2023-05-09 02:35 UTC, KunkelAlexander commented on example/test_problem/Template/Input__Parameter
> +OPT__FFTW_STARTUP            -1           # initialise fftw plans (-1=DEFAULT (MEASURE), 0=ESTIMATE, 1=MEASURE, 2=PATIENT (only FFTW3))
Done

2023-05-09 02:35 UTC, KunkelAlexander commented on src/Init/Init_FFTW.cpp
> +      default:                       StartupFlag = FFTW_MEASURE;
Okay. :)

2023-05-09 05:43 UTC, hyschive approved these changes

2023-05-09 05:43 UTC, merged