Unify all the PRINT_WARNING
gamer-project/gamer pull request #243
Opened 2023-09-27 04:57 UTC by ChunYen-Chen

For solving #170, all the `PRINT_WARNING` is now rewritten as `PRINT_RESET_PARA` defined under `include/Macro.h`.

2023-10-14 13:20 UTC, hyschive requested changes
@ChunYen-Chen Good job. I'll merge it after you address the following comments.
- [ ] Check all inline comments.
- [ ] Replace `FORMAT_FLT` with `FORMAT_REAL` in `Init_ResetParameter.cpp, Init_Set_Default_MG_Parameter.cpp, Init_Set_Default_SOR_Parameter.cpp`
- [ ] Apply `PRINT_RESET_PARA` to `SetParameter()` of `Plummer/Init_TestProb_Hydro_Plummer.cpp` (search the keyword `reset`).

2023-10-14 13:20 UTC, hyschive commented on include/Macro.h
> +         Aux_Message( stderr, "WARNING : parameter [%-28s] is reset to [" EXPAND_AND_QUOTE(format) "] "  \
Increase `28s` to `30s`

2023-10-16 05:53 UTC, ChunYen-Chen commented
@hyschive Thanks for the reviewing. The changes have been made.

2023-10-16 07:43 UTC, hyschive approved these changes

2023-10-16 07:43 UTC, merged

2023-10-17 01:33 UTC, ChunYen-Chen commented
Wrong PR content :(

2024-04-11 06:15 UTC, ChunYen-Chen commented
TEST: resolve #170