`Gamer_CompareData` with mixed-precision
gamer-project/gamer pull request #244
Opened 2023-09-27 08:16 UTC by koarakawaii

Support using `real_par` in `GAMER_CompareData`
* Aim to allow backward compatibility for data dump without `FLOAT8_PAR`
* Support `Array` with float/double data types simultaneously, though may not needed in `GAMER_CompareData`

2024-04-05 08:37 UTC, hyschive requested changes
@koarakawaii The updated tool works well. Good job! Please address all minor comments I added and solve the conflict in `.gitignore` before merging. Thanks.

2024-04-05 08:37 UTC, hyschive commented on tool/analysis/gamer_compare_data/GAMER_Functions/LoadData_HDF5.cpp
> +   }
Consider simplifying the error message as follows.
```
if ( Float8_Par_check_flag != 0  &&  sizeof(real) != sizeof(real_par) )
   Aux_Error( ERROR_INFO, "Must adopt FLOAT8_PAR=FLOAT8 in Makefile when Float8_Par is not stored in the snapshot !!\n" );
```

2024-04-06 03:11 UTC, koarakawaii commented
@hyschive : the file `GAMER_CompareData_hydro_mix-precision` has been removed, and the other comments have been addressed.

2024-04-06 03:31 UTC, hyschive approved these changes

2024-04-06 03:32 UTC, merged