Generalize Par_SortByPos()
gamer-project/gamer pull request #296
Opened 2024-04-09 04:56 UTC by ChunYen-Chen

As the title, this PR solves the request of #292.

2024-04-23 06:37 UTC, hsinhaoHHuang requested changes
I have left some comments. Please take a look. Thanks!
Also, could you please merge with the main branch first so that I can compare the results more clearly?

2024-04-23 06:37 UTC, hsinhaoHHuang commented on src/Miscellaneous/Mis_SortByMultiField.cpp
- How about not using `IdxTable_copy` and updating `IdxTable` directly?
- Is it possible to support user-specified orders (by an array of indices) for sorting fields?
- How about making the recursion more symmetric by only sending the needed  `IdxTable` with size `NSort` into the next recursion?
    - Then, we have to move the initial IdxTable outside this function.

2024-04-24 07:21 UTC, ChunYen-Chen commented
@hsinhaoHHuang The algorithm is updated as reviewed comments. Please help to review the latest version. Thanks!

2024-04-26 02:03 UTC, hsinhaoHHuang requested changes
@ChunYen-Chen Thank you for the update.

I have tested it, and I think it works well.
The sorted results are the same in the Plummer test problem with feedback.

I have only some minor comments now.

2024-04-26 12:45 UTC, hsinhaoHHuang approved these changes

2024-04-26 12:45 UTC, hsinhaoHHuang commented on src/Miscellaneous/Mis_SortByMultiField.cpp
> +   if ( NOrder < 1 )   Aux_Error( ERROR_INFO, "NOrder must be greater than one!!\n" );
"greater than or equal to"

2024-04-26 14:25 UTC, ChunYen-Chen commented
@hsinhaoHHuang Thanks for the detailed comment. I have updated the description of the parameters and changed the function name.

2024-04-27 02:08 UTC, hsinhaoHHuang approved these changes
Great! I have also tested it again. I don't find any further issues. I think everything works well now.

2024-05-13 15:00 UTC, hyschive reviewed
@ChunYen-Chen Looks great! I have added some comments. The only major comment is to add a new API routine so that users do not have to initialize `IdxTable[]` by themselves.

2024-05-13 15:00 UTC, hyschive commented on src/Miscellaneous/Mis_SortByRows.cpp
> +   if ( NSort  < 0 )   Aux_Error( ERROR_INFO, "NSort must be greater than or equal to zero!!\n" );
Simplify the error message as `"NSort < 0 !!\n"`

2024-05-13 15:00 UTC, hyschive commented on src/Miscellaneous/Mis_SortByRows.cpp
> +   if ( NOrder < 1 )   Aux_Error( ERROR_INFO, "NOrder must be greater than or equal to one!!\n" );
Simplify the error message as `"NOrder < 1 !!\n"`

2024-05-13 15:00 UTC, hyschive commented on src/Miscellaneous/Mis_SortByRows.cpp
> +      if ( NOrder == 1 )
Change to `else if ( NOrder == 1 )` to improve clarity.

2024-05-15 06:13 UTC, ChunYen-Chen commented
@hyschive Thanks for your review! I have modified the code according to the comments.

2024-05-15 13:36 UTC, hyschive approved these changes

2024-05-15 13:37 UTC, merged