Support recording angular momentum
gamer-project/gamer pull request #297
Opened 2024-04-11 03:45 UTC by hsinhaoHHuang

### Goal
- To address issue #197 

### Changes
- Record angular momentum (`AngMomX/Y/Z_Gas`, `AngMomX/Y/Z_Par`, `AngMomX_All`) in `Record__Conservation` when `OPT__CK_CONSERVATION` is on.

- Add the runtime option `ANGMOM_ORIGIN_X/Y/Z` to specify the origin coordinates to compute the angular momentum. 
   - The default is the box center.
   - The center cannot change in time so far.

### Validation
- A Python script using `yt` to compute the angular momentum (and other conserved quantities) is added in `example/test_problem/Hydro/Plummer/plot_script/yt_get_conserved_quantities.py`.
   - The results are consistent with `Record__Conservation` for the `Plummer` test problem.

2024-04-13 02:18 UTC, hsinhaoHHuang commented
Implementing recording the center of mass in `Record__Conservation` has been done.

2024-04-15 06:58 UTC, ChunYen-Chen requested changes
The function works well! I only have some minor comments.

2024-04-15 06:58 UTC, ChunYen-Chen commented on example/test_problem/Hydro/Plummer/plot_script/yt_find_center.py
> +field_pote       = ('gamer',    'Pote')
Please notify the user if the `OPT__OUTPUT_POT` or not.

2024-04-15 06:58 UTC, ChunYen-Chen commented on example/test_problem/Hydro/Plummer/plot_script/yt_get_conserved_quantities.py
> +    return 0.5*data['Pote']*data['Dens']*data['cell_volume']
Please notify the user if the `OPT__OUTPUT_POT` or not.

2024-04-15 06:58 UTC, ChunYen-Chen commented on src/Particle/Par_Aux_GetConservedQuantity.cpp
> +         const double dZ   = amr->Par->PosZ[p] - ANGMOM_ORIGIN_Z;
Can you move this part of the code to line 55?

2024-04-18 03:34 UTC, ChunYen-Chen approved these changes

2024-04-18 09:05 UTC, hsinhaoHHuang commented
@hyschive 
When we set `OPT__CORR_AFTER_ALL_SYNC  = 1 (every step)` in `Input__Parameter`,
the total momenta of the particles in `Record__Conservation` are the same as the results computed from `yt` for the final dump.

2024-05-12 04:07 UTC, hyschive reviewed
@hsinhaoHHuang Looks great! I only have minor comments. Once it's merged, please file a follow-up PR to merge `main` into `psidm` and to support angular momentum and CoM for ELBDM.

2024-05-13 05:23 UTC, hsinhaoHHuang commented
@hyschive  Thanks for the review. I have made the updates to this pull request according to your suggestions.

2024-05-13 08:03 UTC, hyschive approved these changes

2024-05-13 08:03 UTC, merged