Define `GPU_COMPUTE_CAPABILITY`
gamer-project/gamer pull request #302
Opened 2024-04-29 01:13 UTC by ChunYen-Chen

Solves #207.

2024-05-13 02:17 UTC, hyschive requested changes
@ChunYen-Chen Good job. In addition to the inline comments, I suggest the following changes/tasks.
- In `CUAPI_SetDevice.cu`, revise the sanity checks on `GPU_ARCH` to compare `GPU_COMPUTE_CAPABILITY` and `DeviceProp.major/minor` directly ([example](https://github.com/hyschive/gamer-fork/blob/psidm/src/GPU_API/CUAPI_SetDevice.cu#L204-L208))
- Update these [comments](https://github.com/gamer-project/gamer/blob/main/example/queue/submit_ncts_intel.job#L45-L51) about mixing TURING and AMPERE on the NCTS cluster (@hfhsieh can help validate it)
- Record `GPU_COMPUTE_CAPABILITY` in `Aux_TakeNote.cpp`
- Once this PR is merged, file a follow-up PR to merge `main` into `psidm`
  - Remove `GPU_COMPUTE_CAPABILITY` from `CUFLU.h` 
  - Update or remove the error message “Please update GPU_COMPUTE_CAPABILITY in CUFLU.h” in `CUAPI_SetDevice.cu`

2024-05-13 02:27 UTC, hfhsieh commented
@hyschive I have not updated this file yet. However, these [comments](https://github.com/gamer-project/gamer/blob/main/example/queue/submit_ncts_intel.job#L45-L51) are deprecated since the computer architecture on the NCTS cluster have been updated (collect the same GPUs into the same node).

2024-05-13 02:33 UTC, hyschive commented
> @hyschive I have not updated this file yet. However, these [comments](https://github.com/gamer-project/gamer/blob/main/example/queue/submit_ncts_intel.job#L45-L51) are deprecated since the computer architecture on the NCTS cluster have been updated (collect the same GPUs into the same node).

@hfhsieh Thanks for the clarification.
@ChunYen-Chen Then you can simply remove those comments.

2024-05-15 04:42 UTC, ChunYen-Chen commented on src/configure.py
> +def get_gpu_compute_capability():
The error is raised correctly for the machine without CUDA. I do not have a device without an NVIDIA GPU, so I did not test it.

2024-05-15 05:54 UTC, ChunYen-Chen commented
@hyschive Thanks for your review! I have modified the script according to the comments. I do not have the machine without any NVIDIA GPU, so I leave the conversion about `get_gpu_compute_capability()` unresolved.

2024-05-18 03:46 UTC, hyschive requested changes
- Set the following Compute Capabilities.
  - `cannon.config`:
    ```
    GPU_COMPUTE_CAPABILITY 800    # NVIDIA A100 
    #GPU_COMPUTE_CAPABILITY 700    # NVIDIA V100
    ```
  - `fomalhaut.config`:
    ```
    GPU_COMPUTE_CAPABILITY 860    # GeForce RTX 3080 and RTX A4000
    #GPU_COMPUTE_CAPABILITY 750    # GeForce RTX 2080 Ti 
       ```
  - `ncts.config`:
    ```
    GPU_COMPUTE_CAPABILITY 860    # RTX A6000 
    #GPU_COMPUTE_CAPABILITY 750    # Quadro RTX 6000
    ```
  - `pleiades.config`:
    ```
    GPU_COMPUTE_CAPABILITY 700    # NVIDIA V100
    ```
- Remove `bluewaters.config` as this system has been decommissioned
- For consistency, how about setting `NVCCFLAG_COM, NVCCFLAG_FLU, NVCCFLAG_POT` completely in `configure.py`, except for `NVCCFLAG_COM += $(COMMONFLAG)`?
- There are many typos in `configure.py`. Check it carefully.
- When enabling `--gpu`, raise an error instead of a warning if `GPU_COMPUTE_CAPABILITY` is not set properly (e.g., when it's not set in `*.config`); you can refer to `../configs/template.config` in the error message.
- Align the following lines in `Makefile.log`
```
GPU_COMPUTE_CAPABILITY : 860
NVCCFLAG_ARCH   : -gencode arch=compute_86,code=\"compute_86,sm_86\"
NVCCFLAG_FLU    : --maxrregcount=192
```

2024-05-18 03:46 UTC, hyschive commented on src/configure.py
> +        # check if the depend is true
Remove "the"

2024-05-18 03:46 UTC, hyschive commented on src/configure.py
> +    # 1. Set the complier.
Typo: complier

2024-05-18 03:46 UTC, hyschive commented on src/configure.py
> +    # 3. Write flags to complie option dictionary.
Typo: complie

2024-05-18 03:46 UTC, hyschive commented on src/configure.py
> +    # 0. Setup logger
"Set the logger"

2024-05-18 03:46 UTC, hyschive commented on src/configure.py
> +    # 1. Get the executed command
"executed" --> "execution"

2024-05-18 03:46 UTC, hyschive commented on src/configure.py
> +    # 3.4 Setup compiler
"Set the compiler"

2024-05-18 03:46 UTC, hyschive commented on src/configure.py
> +    # 3.5 Setup gpus
"Set the GPU"

2024-05-18 03:46 UTC, hyschive commented on src/configure.py
> +    # 0. Checking the Makefile_base existance.
typo: existance

2024-05-21 14:28 UTC, hyschive reviewed
- `GPU_COMPUTE_CAPABILITY` is still missing in several `*.config`. Check my comment [here](https://github.com/gamer-project/gamer/pull/302#pullrequestreview-2063439922) carefully.
- How about executing the following lines in `configure.py` instead of `Makefile_base` to improve the internal consistency further?
```
ifeq "$(filter -DGAMER_DEBUG, $(SIMU_OPTION))" "-DGAMER_DEBUG"
   NVCCFLAG_COM += -g -Xptxas -v   # "-G" may cause the GPU Poisson solver to fail
endif
```
- Modify `CUDAFLAG` in all `*.config` as follows.
  - Replace `--ccbin` with `-ccbin`
  - Combine it with `NVCCFLAG_COM` by
  ```
  NVCCFLAG_COM -O3
  #NVCCFLAG_COM --ccbin YOUR_HOST_COMPILER
  #NVCCFLAG_COM --ccbin CC
  ```
  - Remove `CUDAFLAG` from `configure.py` since it's now part of `NVCCFLAG_COM`.
- Remove the following lines from `*.config` as they are deprecated.
```
#NVCCFLAG_COM -Xcompiler
#NVCCFLAG_COM -Xopencc -OPT:Olimit=0
```

2024-05-21 14:28 UTC, hyschive commented on src/configure.py
> +        if args["gpu"]: raise ValueError("GPU_COMPUTE_CAPABILITY is not set in *.config. Please checkout `../configs/template.config` to see how to set GPU_COMPUTE_CAPABILITY.")
How about changing the error message to
```
"GPU_COMPUTE_CAPABILITY is not set in `../configs/%s.config`. See `../configs/template.config` for illustration." % args["machine"]
```

2024-05-21 14:28 UTC, hyschive commented on src/configure.py
> +    if nGpus.value > 1: print("WARNING: More than one GPU. Selecting the last GPU compute capability.")
Change the warning message to "WARNING: More than one GPU --> select the compute capability of the last GPU."

2024-05-21 14:28 UTC, hyschive commented on src/configure.py
> +def get_gpu_compute_capability():
@ChunYen-Chen Have you tested it on a system without any NVIDIA GPU (e.g., on a MacBook)?

2024-05-22 04:21 UTC, ChunYen-Chen commented
@hyschive Thanks for your review. I have changed the code according to the comments.

2024-05-22 06:32 UTC, hyschive approved these changes
@ChunYen-Chen Looks good. I'll merge it right away!

There is a typo `GPU_COMPUTABILITY` in `template.config` but I'll fix it by myself.

2024-05-22 06:32 UTC, merged