Record user data in HDF5
gamer-project/gamer pull request #304
Opened 2024-05-06 16:15 UTC by ChunYen-Chen

This PR allows users to record their parameters in HDF5(`Data_*`). It supports storing the data types: `int`, `uint`, `long`, `ulong`, `bool`, `float`, `double`, and `string` (`char *`).

## How to use it
1. Create a function called `void HDF5_Output_User_<YourTestProblem>( HDF5_OutUser_t *HDF5_OutUser )` in your test problem initialize file (`Init_TestProb_<YourTestProblem>.cpp`). Please replace the `<YourTestProblem>` with your test problem name.
1. Please wrap the function with preprocessor directives `#ifdef SUPPORT_HDF5` and `#endif`.
1. Add the parameters you would like to store by adding the following line in the function `HDF5_Output_User_<YourTestProblem>`:
   ```C++
   HDF5_OutUser->Add( "Parameter_Key", &parameter_to_store );
   ```
1. At the end, you should have the function like:
   ```C++
   #ifdef SUPPORT_HDF5
   void HDF5_Output_User_YourTestProblem( HDF5_OutUser_t *HDF5_OutUser )
   {
      ...
      HDF5_OutUser->Add( "Parameter_Key1", &parameter_to_store1 );
      HDF5_OutUser->Add( "Parameter_Key2", &parameter_to_store2 );
      ...
   }
   #endif
   ```
1. Add the following lines at the end of the function `Init_TestProb_<YourTestProblem>()`.
   ```
   #ifdef SUPPORT_HDF5
   HDF5_Output_User_Ptr = HDF5_Output_User_<YourTestProblem>;
   #endif
   ```
1. An example usage is provided at `Init_TestProb_Hydro_Plummer.cpp`.

## Where it stored
The parameters are stored under the `Info` group -> `Output_User` group.

## How to get the data from HDF5
Here I provide a simple Python script to show all the data stored under the `Output_User` group.
```python
import h5py
f = h5py.File( "Data_000000", "r" )
for key, val in f["Info"]["Output_User"].items():
    try:
        print("%-20s : %.14e"%(key, val[()]))
    except:
        # string type
        print("%-20s : "%(key), end="")
        print(val[()])
```
You will see something like:
```
Merger_Coll_IsGas1   : 2.57000000000000e+02
Merger_Coll_IsGas2   : 1.00000000000000e+00
Merger_Coll_IsGas3   : 0.00000000000000e+00
Merger_Coll_NumHalos : 2.00000000000000e+00
Merger_Coll_PosX1    : 6.00000000000000e+00
Merger_Coll_PosX2    : 9.00000000000000e+00
Merger_Coll_PosX3    : 0.00000000000000e+00
Merger_Coll_PosY1    : 7.50000000000000e+00
Merger_Coll_PosY2    : 7.50000000000000e+00
Merger_Coll_PosY3    : 0.00000000000000e+00
Merger_Coll_UseMetals : 0.00000000000000e+00
Merger_Coll_VelX1    : 3.83508861100314e+00
Merger_Coll_VelX2    : -1.15052658330094e+01
Merger_Coll_VelX3    : 0.00000000000000e+00
Merger_Coll_VelY1    : 0.00000000000000e+00
Merger_Coll_VelY2    : 0.00000000000000e+00
Merger_Coll_VelY3    : 0.00000000000000e+00
Merger_File_Par1     : b'1to3_b0.0_gamerp_1.h5'
Merger_File_Par2     : b'1to3_b0.0_gamerp_2.h5'
Merger_File_Par3     : b'none'
Merger_File_Prof1    : b'profile1_gamer.h5'
Merger_File_Prof2    : b'profile2_gamer.h5'
Merger_File_Prof3    : b'none'
```

This PR resolves #70.

2024-08-09 12:20 UTC, hsinhaoHHuang requested changes
I can run the `Plummer` test problem and see those `Input__TestProb` variables correctly stored in the HDF5 file.

I have some questions:
1. It seems to me this PR only resolves part of the issue #70 
    - It does provide an easy interface for test problems to store arbitrary variables.
    - It still does not record the variables loaded from `Input__TestProb` in the HDF5 snapshots for most of the test problems. That means someone still has to finish this job by adding `HDF5_Output_User_XXX` in every test problem.
    - Different from "user data", which may be some evolved results the user wants to record, I would expect those loaded from `Input__TestProb` stored in an HDF5 dataset named something like `InputTestProb`.

2. Why are those `Input__TestProb` variables saved as an HDF5 group in "Info" and each parameter inside is an HDF5 dataset?
    - It is different from other parameters in `Input__Parameter`, which are saved in a single HDF5 dataset `InputPara`.
    - Is it possible to use a similar way as `GetCompound_InputPara()` and `FillIn_InputPara()` in `src/Output/Output_DumpData_Total_HDF5.cpp`to save them in a compound datatype?
    - On the other hand, I think we could save the user-recorded data, e.g. the BH_variable.bin mentioned in the issue, in another HDF5 Group parallel to GridData.
    - To be more specific, I would expect something like
```
 / -> |
      | -> Info group     -> | -> InputPara     dset (compound)
      |                      | -> InputTestProb dset (compound)
      |                      | -> KeyInfo       dset (compound)
      |                      | -> Makefile      dset (compound)
      |                      | -> SymConst      dset (compound)
      |                              
      | -> UserData group -> | -> BH_variable dset
      |                              
      | -> GridData group -> | -> Dens dset
```

   - At least, now it will cause an error when loading data in yt script, where the GAMER frontend expects there are datasets in the HDF5 Gruop "Info":
```python
File /work1/hsinhao/software/miniconda2/envs/dev4/lib/python3.9/site-packages/yt/frontends/gamer/data_structures.py:292, in GAMERDataset._parse_parameter_file(self)
    290 for t in self._handle["Info"]:
    291     info_category = self._handle["Info"][t]
--> 292     for v in info_category.dtype.names:
    293         self.parameters[v] = info_category[v]
    295 # shortcut for self.parameters

AttributeError: 'Group' object has no attribute 'dtype'
```

3. A minor comment: The example HDF5 data results provided in the PR conversation are not from the Plummer test problem you implemented.

2024-08-29 10:00 UTC, ChunYen-Chen commented
@hsinhaoHHuang I have updated this PR. Please take another review. Thanks!

2024-10-16 09:11 UTC, hsinhaoHHuang reviewed
@ChunYen-Chen Thank you for updating this PR and solving the previous issues. It looks great now! :tada: 

I have checked the parameters in `Input_TestPrb` are properly stored in the HDF5 data for some selected test problems.
I also tried to store the various user parameters using the Plummer test problem.

I only have one issue during my tests.
- It seems the string variables only store the first character. For example, in the hdf5 data of the `ClusterMerger` test problem,
   ```
   Merger_File_Prof1  = b'p'                                                                   
   Merger_File_Par1   = b'1'
   Merger_File_Prof2  = b'p'
   Merger_File_Par2   = b'1'
   Merger_File_Prof3  = b'n'
   Merger_File_Par3   = b'n'
   ``` 


I also have some questions:
- Is it possible to store an array, e.g. `NX0_Tot = [128, 128, 128]`, in the User data?
- Do you know how to access the parameters stored in the `User` Group using `yt` in a similar way as this:
   ```python
   import yt
   ds = yt.load('./Data_000000')
   print( ds.parameters["BoxSize"] )
   print( ds.parameters["Plummer_BulkVelX"] )
   ```
   or I can only use `h5py` to access them.


And some minor suggestions:
- For other reviewers, could you also update the description in the conversation in this PR, which has been different from the latest code?
- It will be great if there is one real test problem to use the ` HDF5_Output_User_Ptr` to store the user data as a practical example.
- Some other comments are added inline.

2024-10-16 20:43 UTC, ChunYen-Chen reviewed
Thanks for the review! I have updated the code according to the comments.

2024-10-16 20:43 UTC, ChunYen-Chen commented on src/TestProblem/Template/Init_TestProb_Template.cpp
> +   HDF5_Output_User_Ptr              = NULL; //                                       example: Output/Output_DumData_Total_HDF5.cpp --> HDF5_Output_User_Example()
Updated

2024-10-16 20:43 UTC, ChunYen-Chen commented on src/TestProblem/Hydro/CDM_LSS/Init_TestProb_Hydro_CDM_LSS.cpp
> +   char Empty[MAX_STRING] = "Empty";
I changed to store the test problem id which is a global variable.

2024-10-16 20:43 UTC, ChunYen-Chen commented on doc/wiki/Adding-New-Simulations.md
> +None
Added

2024-10-16 20:43 UTC, ChunYen-Chen commented on doc/wiki/Adding-New-Simulations.md
> +## IX. Store Problem-specific Variables
Moved

2024-10-16 20:43 UTC, ChunYen-Chen commented on src/Output/Output_DumpData_Total_HDF5.cpp
> +static void GetCompound_HDF5_Output( hid_t &H5_TypeID, const HDF5_Output_t *HDF5_OutUser );
Renamed as `GetCompound_General`

2024-10-16 21:02 UTC, ChunYen-Chen commented
@hsinhaoHHuang Thanks for the review, comments, and issue report!
> * It seems the string variables only store the first character. For example, in the hdf5 data of the `ClusterMerger` test problem,
>   ```
>   Merger_File_Prof1  = b'p'                                                                   
>   Merger_File_Par1   = b'1'
>   Merger_File_Prof2  = b'p'
>   Merger_File_Par2   = b'1'
>   Merger_File_Prof3  = b'n'
>   Merger_File_Par3   = b'n'
>   ```

I also encounter the same issue, I will update the code once the bug is fixed.

> * Is it possible to store an array, e.g. `NX0_Tot = [128, 128, 128]`, in the User data?

I think it is possible, but I have not tried it in this PR.

> * Do you know how to access the parameters stored in the `User` Group using `yt` in a similar way as this:
>   ```python
>   import yt
>   ds = yt.load('./Data_000000')
>   print( ds.parameters["BoxSize"] )
>   print( ds.parameters["Plummer_BulkVelX"] )
>   ```     
>
>   or I can only use `h5py` to access them.

I do not know if there is a way to access them in `yt`. If the frontend of `yt` is not updated to this version of GAMER, I do not think there is a way to access it through `yt`.

> * It will be great if there is one real test problem to use the ` HDF5_Output_User_Ptr` to store the user data as a practical example.

There will soon be an example using `HDF5_Output_User_Ptr`. See #339 and https://github.com/ShuangShuang0411/gamer-fork/pull/1.

2024-10-17 01:44 UTC, hsinhaoHHuang commented on doc/wiki/Adding-New-Simulations.md
> +## IX. Store Problem-specific Variables
I am sorry I didn't make it clear. I actually meant between "3." and "4." inside "IV. Add Problem-specific Parameters"
![Screenshot from 2024-10-17 09-42-30](https://github.com/user-attachments/assets/d8830e6a-ef93-4f4d-8edb-dc87b26979c5)

2024-10-17 01:49 UTC, hsinhaoHHuang commented
Thank you for the update! A quick question: I cannot compile it now, probably due to the renaming.
```
Output/Output_DumpData_Total_HDF5.cpp(461): error: identifier "GetCompound_Output" is undefined
        GetCompound_Output   ( H5_TypeID_Com_InputTest, &HDF5_InputTest );
        ^

compilation aborted for Output/Output_DumpData_Total_HDF5.cpp (code 2)
```
I hope it is easy to fix it. Thanks!

2024-10-17 02:24 UTC, ChunYen-Chen commented on doc/wiki/Adding-New-Simulations.md
> +## IX. Store Problem-specific Variables
Updated!

2024-10-17 06:41 UTC, hsinhaoHHuang approved these changes
Great! Approved! :tada: 
I have no further comments.
Thank you for resolving all the issues and updating the PR.

2024-12-15 13:47 UTC, hyschive commented
@ChunYen-Chen I don't quite understand why we need to separate "Store User data in HDF5" and "Store test problem variables in HDF5". I thought "user" and "test problem" mean the same thing in GAMER. We can discuss it in the lab next week.

2024-12-16 06:29 UTC, ChunYen-Chen commented
@hyschive This setup is suggested by @hsinhaoHHuang. ([here](https://github.com/gamer-project/gamer/pull/304#pullrequestreview-2230055489))

2024-12-18 03:15 UTC, hyschive commented
@ChunYen-Chen @hsinhaoHHuang Thanks for the clarification. I see what you want to achieve by separating `Output_HDF5_TestProb_Ptr` and `Output_HDF5_User_Ptr`, which I agree. Just two minor comments.
- How about renaming `Output_HDF5_TestProb_Ptr` as, for example, `Output_HDF5_InputTest_Ptr` to conform with the HDF5 data layout `Info group -> InputTest` and to explicitly clarify that it's only used for `Input__TestProb`? Otherwise, `TestProb` and `User` sound similar to me. If you agree, modify other related parameters/variables/routines as well (e.g., `Output_HDF5_TestProb`).
- To minimize redundant codes, would it be possible to combine the code lines of `ReadPara->Add()` and  `HDF5_InputTest->Add()`? For example, we can have a single unified routine `LoadInputTestProb()` as follows and both call it by `SetParameter()` and link it to `Output_HDF5_TestProb_Ptr`. Within this unified routine, we use a macro to call either `ReadPara->Add()` or  `HDF5_InputTest->Add()`, decided by a function argument.
```
void LoadInputTestProb()
{
   Macro( "Merger_Coll_NumHalos",    &Merger_Coll_NumHalos,     2,                1,             3              );
}
```

2025-01-15 08:40 UTC, hyschive commented
@ChunYen-Chen Please resolve the conflicts.

2025-02-15 02:27 UTC, hyschive requested changes
@ChunYen-Chen Looks great! I've added some minor comments, mainly focusing on renaming variables and functions to better distinguish the following terms:
- `InputTest`: for parameters in `Input__TestProb`, handled by `Output_HDF5_InputTest_Ptr` and stored in `/Info/InputTest`
- `UserPara`: for user-specified parameters, handled by `Output_HDF5_UserPara_Ptr` and stored in `/User/UserPara`
- `General, Output, ...`: for general-purpose variables used by both `InputTest` and `UserPara`

Notes:
- In some places, I replaced `User` (and `OutUser`) with `UserPara` to clarify that it stores all user-specified _parameters_ and to better distinguish it from other variables (e.g., a GREP profile) that can also be placed in the `User` group.
- I replaced `OutUser` with `Output` if it's general-purposes (i.e,. variables/functions used by both `InputTest` and `UserPara`)

Other general comments:
- @jzuhone Once this PR is merged, please merge it into `cool-core-public`
- In principle, we could utilize `AddInputTestPara()` in `Init_Load_Parameter()` as well. How about submitting a feature request?
- Resolve the conflicts

2025-03-06 03:12 UTC, ChunYen-Chen commented on include/HDF5_Typedef.h
> +      NewPtr[MAX_STRING-1] = '\0';
I don’t think so, since `fgets()` only reads up to `MAX_STRING` characters per line. ([ref](https://github.com/gamer-project/gamer/blob/2d474e3a6e91a628b579f1bdcfb1eb7e97615f75/include/ReadPara.h#L245))

2025-03-15 02:36 UTC, hyschive commented on include/HDF5_Typedef.h
> +      NewPtr[MAX_STRING-1] = '\0';
I'm just curious why you only add `'\0'` here but not in all other instances of `strncpy()` calls in `ReadPara.h` and `HDF5_Typedef.h`.

It seems that many parts of the current code implicitly assume that string lengths are shorter than `MAX_STRING`. In other words, if a string length is exactly equal to `MAX_STRING`, unexpected results would happen in multiple places, not just here.

Given this, we either fix all instances where this assumption is made (which is beyond the scope of this PR) or remove the line `NewPtr[MAX_STRING-1] = '\0';` here to avoid possible confusion and maintain consistency with the rest of the code.

What do you think?

2025-03-15 03:55 UTC, hyschive reviewed
@ChunYen-Chen Thanks for the update! I have only a few minor comments before merging.

2025-03-15 03:55 UTC, hyschive commented on src/TestProblem/ELBDM/HaloMerger/Init_TestProb_ELBDM_HaloMerger.cpp
> +// Description :  Template for storing user-specified parameters in an HDF5 snapshot at User/UserPara
```suggestion
// Description :  Store user-specified parameters in an HDF5 snapshot at User/UserPara
```

2025-03-16 03:46 UTC, ChunYen-Chen commented on include/HDF5_Typedef.h
> +      NewPtr[MAX_STRING-1] = '\0';
Got it. I removed this code.

2025-03-16 04:02 UTC, hyschive approved these changes

2025-03-16 04:02 UTC, merged