Update AGORA test problem: High-res ICs [Reviewed]
gamer-project/gamer pull request #346
Opened 2024-08-26 14:34 UTC by BarryTC

with comments from ChunYen-Chen addressed

2024-08-28 05:45 UTC, ChunYen-Chen approved these changes
Looks Great. I only have some minor comments.

2024-08-28 05:45 UTC, ChunYen-Chen commented on example/grackle/Make.mach.eureka-intel
> +MACH_INSTALL_PREFIX = MACH_INSTALL_PREFIX = <local_grackle_directory>/grackle/grackle_eureka_single_omp
There is one extra `MACH_INSTALL_PREFIX`. Please remove it.

2024-08-28 05:45 UTC, ChunYen-Chen commented on example/grackle/README
> +    (1) Add the path "GRACKLE_PATH    <your_grackle_directory>/grackle/grackle_spock_single_omp" to "<your_gamer_directory>/configs/spock_intel.config"
The path `GRACKLE_PATH` is different from step 4. You might want it to be `<your_grackle_directory>/grackle_spock`.

2024-08-28 05:45 UTC, ChunYen-Chen commented on example/grackle/Make.mach.eureka-intel
> +# DATE:        April 1, 2016
Please update the file information.

2024-08-28 05:45 UTC, ChunYen-Chen commented on example/grackle/Make.mach.spock-intel
> +# DATE:        April 1, 2016
Please update the file information.

2024-12-26 05:40 UTC, ChunYen-Chen commented
@BarryTC Your `download_ic_high.sh` in this PR does not work, but the `download_ic_high.sh` in the previous PR #344 works. Could you check the link in the script? (@hsinhaoHHuang)

2024-12-27 07:58 UTC, ChunYen-Chen commented on example/grackle/Make.mach.spock-intel
> +#              and Yen-Chen Chun)
[Typo] Chun-Yen Chen

2024-12-31 03:15 UTC, hsinhaoHHuang commented on example/test_problem/Hydro/AGORA_IsolatedGalaxy/README
> +
Dear @BarryTC (and @hyschive),

I have recently tried to reproduce the results of the AGORA isolated galaxy in the [GAMER-2 paper](https://doi.org/10.1093/mnras/sty2586).
Thank you for preparing this pull request. It helps me a lot.

Following your setups of high-resolution runs, here is my result of the star formation rate (to be compared to Figure 17. in the GAMER-2 paper):
![image](https://github.com/user-attachments/assets/eb650766-e370-4c16-a3c2-bd8351313dbf)
May I confirm with you whether this is consistent with your results?


When I compared this test problem in GAMER to the GAMER-2 paper, I found that besides the high-resolution IC, `PAR_NPAR` and `MAX_LEVEL`, it seems we also need to adjust the star formation parameters and the refinement criteria.

### Additional Changes
- In Section 4.4.1 of the GAMER-2 paper, the gas density threshold is $n_\mathrm{H,thres} = 20\ \mathrm{cm}^{-3}$
   - In "Input__Parameter",
     the default `SF_CREATE_STAR_MIN_GAS_DENS   5.0e0` should be changed to
     `SF_CREATE_STAR_MIN_GAS_DENS   2.0e1`.
- In Section 4.4.1 of the GAMER-2 paper, the minimum star particle mass is $m_{*} = 2\times 10^{3}\ M_\odot$
   - In "Input__Parameter",
     the default `SF_CREATE_STAR_MIN_STAR_MASS  3.2e4` should be changed to
     `SF_CREATE_STAR_MIN_STAR_MASS  2.0e3`.
- In Table 3. of the GAMER-2 paper, the maximum particle mass in a cell is $1\times 10^6\ M_\odot$.
   - In "Input__Flag_ParMassCell",
     the default `1.0035496e-1` should be changed to
     `1.0035496e-3`.
- In Table 3. of the GAMER-2 paper, the maximum gas mass in a cell is $3.4\times 10^{2}\ M_\odot$.
   - In "Input__Flag_Rho",
     the default
     ```
     # Level                    Density
      0           2.000480890274048e-08
      1           1.600384712219238e-07
      2           1.280307769775391e-06
      3           1.024246215820313e-05
      4           8.193969726562500e-05
      5           6.555175781250000e-04
      6           5.244140625000000e-03
      7           4.195312500000000e-02
      8           3.356250000000000e-01
      9           2.685000000000000e-00
     10           2.148000000000000e+01
     ```
     should be changed to
     ```
     # Level                    Density
      0           3.201222978532314e-10
      1           2.560978382825851e-09
      2           2.048782706260681e-08
      3           1.639026165008545e-07
      4           1.311220932006836e-06
      5           1.048976745605469e-05
      6           8.391813964843749e-05
      7           6.713451171875000e-04
      8           5.370760937500000e-03
      9           4.296608750000000e-02
     10           3.437287000000000e-01
     ```
- In Table 3. of the GAMER-2 paper, the refinement resolves Jeans length by at least $64$ cells.
   - In "Input__Flag_Jeans",
     the default `32.0` should be changed to
     `64.0`

### Results
Including the above changes, here is the resulting star formation rate:
![image](https://github.com/user-attachments/assets/9a46c00e-d1a0-40c5-b969-2128c352dc15)
I think it looks better.

Could you help me check whether these changes make sense?
Thanks!


### Note
- There are still some differences remained:
   - In Table 3. of the GAMER-2 paper, it said "Root grid $64^3$, $10$ refinement levels" and "Five additional levels of statically refined regions above the root grid".
   - In GAMER, it actually is root grid $128^{3}$, $9$ refinement levels, and 4 statically refined levels.
- I am using the single-precision GAMER with the double-precision GRACKLE (as recommended), supported in https://github.com/gamer-project/gamer/pull/365

2024-12-31 03:15 UTC, hsinhaoHHuang commented on example/test_problem/Hydro/AGORA_IsolatedGalaxy/README
At Line 15., I think it should be `[M] = 1.0e9 Msun` as the `UNIT_M` is `1.9885e42` g in `Input__Parameter`.

2024-12-31 10:41 UTC, hsinhaoHHuang commented on example/test_problem/Hydro/AGORA_IsolatedGalaxy/README
> +
A minor difference is found in @hyschive's previous `Input__Flag_Rho`, which corresponds to the maximum gas mass in a cell is $335.625\ M_\odot$ and is $1/64$ of the default criteria:
```
# Level                         Density
      0           3.125751391053200e-10
      1           2.500601112842560e-09
      2           2.000480890274048e-08
      3           1.600384712219238e-07
      4           1.280307769775391e-06
      5           1.024246215820313e-05
      6           8.193969726562500e-05
      7           6.555175781250000e-04
      8           5.244140625000000e-03
```

, while my `Input__Flag_Rho` provided in the previous comment is set to the maximum gas mass in a cell = $343.729\ M_\odot$ ($= 0.1\times$ mass of each particle in the initial conditions of the disk and the bulge).

2025-01-01 10:51 UTC, hyschive commented on example/test_problem/Hydro/AGORA_IsolatedGalaxy/README
> +
@BarryTC @hsinhaoHHuang How about having separate runtime files for the low- and high-resolution runs? We then choose the low-resolution case by default. For example,
```
Input__Parameter.low-res
Input__Parameter.high-res
ln -s Input__Parameter.low-res Input__Parameter
```

2025-01-02 20:03 UTC, BarryTC commented on example/test_problem/Hydro/AGORA_IsolatedGalaxy/README
> +
@hsinhaoHHuang Thank you again for the super detailed cross-checks.
1. The high-resolution run under the previous (low-res) star formation and refinement criteria yields a SFR consistent with your first plot: 
![fig__star_formation_rate](https://github.com/user-attachments/assets/c678887c-6a9d-45ab-a63e-2eafa58108a7)
2. Following @hyschive's suggestions, I have updated README and "download_ic" and "download_ic_high_res". Now executing "sh download_ic*" both downloads the AGORA ICs as well as soft-linking all the Input_* files. It would be greatly appreciated if you could verify again that all the files work as intended to.

To @hyschive, this PR should be ready to merge AFTER the Dropbox link for high-res AGORA ICs has been updated (#390)!

2025-01-05 09:12 UTC, hsinhaoHHuang commented on example/test_problem/Hydro/AGORA_IsolatedGalaxy/README
> +
Hi @BarryTC
Thank you for the confirmation and the update.

- The adopted `Input__Flag_Rho.high-res` is just my guess based on the description in the GAMER-2 paper. Since Prof. Schive shared with me the original input files, I think we should follow the setup of `Input__Flag_Rho` as:
   ```
   # Level                         Density
         0           3.125751391053200e-10
         1           2.500601112842560e-09
         2           2.000480890274048e-08
         3           1.600384712219238e-07
         4           1.280307769775391e-06
         5           1.024246215820313e-05
         6           8.193969726562500e-05
         7           6.555175781250000e-04
         8           5.244140625000000e-03
   ```
- I noticed you also changed the `Input__Parameter` to `NX0_TOT_* = 64` and `MAX_LEVEL = 10`, which is consistent with the description in the GAMER-2 paper. However, I am not sure whether this would be better from the perspective of resolution.
   @hyschive What's your suggestion? 
   The `Input__Parameter` that Prof. Schive gives me actually uses `NX0_TOT_* = 128` and `MAX_LEVEL = 9`. If we decided to use `NX0_TOT_* = 64` and `MAX_LEVEL = 10`, I think we also need to change `Input__Flag_Rho`:
   ```
   # Level                         Density
         0           3.907189238816500e-11
         1           3.125751391053200e-10
         2           2.500601112842560e-09
         3           2.000480890274048e-08
         4           1.600384712219238e-07
         5           1.280307769775391e-06
         6           1.024246215820313e-05
         7           8.193969726562500e-05
         8           6.555175781250000e-04
         9           5.244140625000000e-03
   ```
   and `Input__Flag_User`:
   ```
   # Level           User-defined_criteria
         0                          327.68
         1                          491.52 
         2                          573.44
         3                          614.40
         4                          634.88
         5                          1.0e30
         6                          1.0e30
         7                          1.0e30
         8                          1.0e30
         9                          1.0e30
   ```
- When I executed your `download_ic.sh` and `download_ic_high_res.sh` on eureka, I found the soft link file name ended with `?`. It seems related to [this issue](https://stackoverflow.com/questions/37566064/why-questionmark-comes-in-the-end-of-filename-when-i-create-txt-file-through-sh).

2025-01-05 09:34 UTC, hyschive commented on example/test_problem/Hydro/AGORA_IsolatedGalaxy/README
> +
Let's adopt `NX0_TOT_* = 128` and `MAX_LEVEL = 9` for better performance. IIRC, the entire base level will be refined to 128^3 when adopting `NX0_TOT_* = 64` anyway.

2025-01-07 01:11 UTC, hsinhaoHHuang approved these changes

2025-01-08 09:51 UTC, ChunYen-Chen commented
@BarryTC
Could you update the download link of the `HI.tar.gz` according to #390? I have uploaded `HI.tar.gz` to ythub. The link to `HI.tar.gz` is 
```
https://hub.yt/api/v1/item/677e4757999605c485c8de92/download
```

An example of the download script:
```bash
#!/bin/bash

LOCAL_FILENAME1="HI"
LOCAL_FILENAME2="CloudyData_UVB=HM2012.h5"
FILE_ID1="677e4757999605c485c8de92"
FILE_ID2="677ca211999605c485c8de6c"

# 1. download
curl https://hub.yt/api/v1/item/${FILE_ID1}/download -o "${LOCAL_FILENAME1}.tar.gz"
curl https://hub.yt/api/v1/item/${FILE_ID2}/download -o "${LOCAL_FILENAME2}"

# 2. unzip
tar xzvf ${LOCAL_FILENAME1}.tar.gz
mv ${LOCAL_FILENAME1}/*.dat ./
rmdir ${LOCAL_FILENAME1}
rm ${LOCAL_FILENAME1}.tar.gz
```
See also #408.

2025-01-08 13:49 UTC, BarryTC commented on example/test_problem/Hydro/AGORA_IsolatedGalaxy/README
> +
@ChunYen-Chen Thanks for providing the uploaded IC links!
@hsinhaoHHuang Would you mind quickly testing again that the both updated download.sh scripts work as intended? If so, then all the comments are addressed and this PR is ready for merge (@hyschive)!

2025-01-09 02:00 UTC, hsinhaoHHuang approved these changes
@ChunYen-Chen @BarryTC 
I think it is good to download all the data we need from our ytHub, as we don't need to worry about files moving or changing from the source.
However, since the data in this test problem is from others, I would suggest we provide the link or reference to the original sources in the README or comments in this script. In this way, we could let users know where to find the original data (and it also serves as an alternative way to download the data if our links fail).
For example, the `CloudyData_UVB=HM2012.h5` is from [Grackle](https://github.com/grackle-project/grackle_data_files/raw/main/input/).
Are the AGORA HI and LOW from this link: http://goo.gl/8JzbIJ ?

2025-01-09 02:05 UTC, hsinhaoHHuang commented on example/test_problem/Hydro/AGORA_IsolatedGalaxy/README
> +
I have tested it. The updated scripts work well!

2025-01-09 02:05 UTC, BarryTC commented on example/test_problem/Hydro/AGORA_IsolatedGalaxy/download_ic_high_res.sh
> +mv ${LOCAL_FILENAME1}/*.dat ./
To your first comment, I certainly agree (also it'll be easier for future tracking) and I'll update the README file accordingly. As for the second edit, I have no issue with that and will update the ".sh" file accordingly!

2025-01-09 02:16 UTC, BarryTC commented on example/test_problem/Hydro/AGORA_IsolatedGalaxy/download_ic_high_res.sh
> +mv ${LOCAL_FILENAME1}/*.dat ./
@hsinhaoHHuang Done!

2025-01-09 02:29 UTC, hsinhaoHHuang commented on example/test_problem/Hydro/AGORA_IsolatedGalaxy/download_ic_high_res.sh
> +mv ${LOCAL_FILENAME1}/*.dat ./
@BarryTC Thanks!

2025-01-09 02:30 UTC, hsinhaoHHuang approved these changes

2025-01-12 04:15 UTC, hyschive requested changes
@BarryTC Thanks for the contribution! I've added some minor inline comments. Additionally:
- [ ] Fix the conflicts
- [ ] Merge the latest `main` branch, then test whether you can run Graklce with double precision and GAMER with single precision for AGORA successfully.

2025-01-15 15:34 UTC, BarryTC commented on example/grackle/README
> +6. Next execute "make show-config" and "make precision-32" (single precision is more compatible with gaming GPUs on eureka and spock) and "make omp-on" (GAMER does utilize OpenMP)
I have incorporated all the remaining comments and the AGORA test problem can be executed successfully after these commits!

2025-01-16 03:06 UTC, hyschive approved these changes
@BarryTC Everything looks good. Thanks for the contribution!

2025-01-16 03:07 UTC, merged