Add integer attribute of particle
gamer-project/gamer pull request #348
Opened 2024-08-27 05:04 UTC by ChunYen-Chen

This PR allows the user to use integer attributes of particles.

# Changes
* `PAR_TYPE` is now a built-in integer attribute.
* Loading `PAR_IC` is updated.
* Wiki pages about particles are updated.
* Rename `PAR_NATT_USER` to `PAR_NATT_FLT_USER`.

# New
* A new script `create_PAR_IC.cpp` to generate new `PAR_IC` files.
* A new compilation option `INT8_PAR` (`--long_par` in `configure.py`) to control the precision of the integer attributes.
* A new compilation option `PAR_NATT_INT_USER` (`--par_attribute_int` in `configure.py`).

# Note
* `yt` module does not recognize the integer attribute type correctly.
* `gamer_compare_data` is not supported yet.

2024-12-25 02:26 UTC, hyschive commented
@ChunYen-Chen Please update this PR to use the integer type for the `ParHalo` attribute added in #330

2024-12-26 05:28 UTC, hyschive commented
@ChunYen-Chen One quick comment. `PAR_NATT_TOTAL, PAR_NATT_USER, PAR_NATT_STORED` are still mentioned in the following places:
- [ ] `doc/wiki/Simulation-Logs:-Record__Note.md`
- [ ] `example/test_problem/Hydro/AGORA_IsolatedGalaxy/Input__TestProb`
- [ ] `src/TestProblem/Hydro/AGORA_IsolatedGalaxy/Init_TestProb_Hydro_AGORA_IsolatedGalaxy.cpp`

2024-12-27 02:23 UTC, hyschive commented
@ChunYen-Chen In `Output_DumpData_Total.cpp`, particle floating-point data are stored as `real` instead of `real_par`. This is an existing bug that predates this PR. Could you fix it and also check `Init_ByRestart_v2.cpp`? Test it.

2024-12-27 03:31 UTC, ChunYen-Chen commented
@hyschive I discussed with @koarakawaii about this bug. We both think it is fine since we make sure `real` and `real_par` are the same type when enabling `OPT__OUTPUT_TOTAL == OUTPUT_FORMAT_CBINARY` ([source code](https://github.com/gamer-project/gamer/blob/73f2af4e30d7c50397f7fccb5c6f7261a8e96da6/src/Auxiliary/Aux_Check_Parameter.cpp#L366-L371)).

2024-12-27 03:47 UTC, hyschive commented
@ChunYen-Chen @koarakawaii I see. So this is not really a bug.
- Do you remember why we impose this constraint?
- For clarity, we should still use `real_par` instead of `real` when dumping particle data. Do you agree?

2024-12-27 03:50 UTC, ChunYen-Chen commented
@hyschive 

> Do you remember why we impose this constraint?

Perhaps @koarakawaii remembers the reason. 😅 

> For clarity, we should still use real_par instead of real when dumping particle data. Do you agree?

Agree.

2024-12-28 01:44 UTC, hyschive commented
@Chun-Yen-Chen, the `PAR_IC` file in the `CDM_LSS` test is not functioning properly as it still uses the floating-point data type for the particle type. I suggest updating the `PAR_IC` file to align with the new format, and also updating `download_ic.sh` accordingly.

What are your thoughts?

2024-12-28 06:02 UTC, ChunYen-Chen commented
@hyschive Agree, but we do not have any checks to verify if the `PAR_IC` matches the latest version since `PAR_IC` only stores data. This change does not have backward compatibility.

2024-12-28 07:44 UTC, hyschive commented
@ChunYen-Chen We don't need to worry about backward compatibility since this test problem is just a demo. Users just need to download the updated `PAR_IC`.

2024-12-29 09:02 UTC, hyschive requested changes
@ChunYen-Chen Excellent work! I've added comments to your PR. Most of them are minor, except for a few bugs marked as `[BUG]`. In addition, please address the following tasks.
- [ ] Use `real_par` for the C-binary snapshots (refer this [comment](https://github.com/gamer-project/gamer/pull/348#issuecomment-2563244586))
- [ ] Fix `PAR_IC` in the `CDM_LSS` test (refer this [comment](https://github.com/gamer-project/gamer/pull/348#issuecomment-2564133206))
- [ ] Replace `ParType == 0.0` with `ParType == 0` at line 97 in `./example/test_problem/Hydro/ParticleTest/check_mesh2tracer.py`
- [ ] Add support for the tool `gamer_compare_data`, ensuring backward compatibility.
- [ ] Add support for the tool `gamer_extract_profile`, ensuring backward compatibility.

2024-12-31 15:54 UTC, hyschive commented
@ChunYen-Chen Add `PAR_IC_INT8` to wiki

2025-01-06 05:34 UTC, ChunYen-Chen commented on src/Particle/LoadBalance/Par_LB_SendParticleData.cpp
> +         // TODO: NVar is wrong
I expect to be able to calculate the size of the data transferred by `NVar`. The current format does not have enough information to calculate the size.
If printing `NParAttFlt+NParAttInt` is fine, I will keep this format.

2025-01-06 05:38 UTC, hyschive commented on src/Particle/LoadBalance/Par_LB_SendParticleData.cpp
> +         // TODO: NVar is wrong
`NParAttFlt+NParAttInt` is fine

2025-01-07 03:16 UTC, ChunYen-Chen commented on src/TestProblem/ELBDM/DiskHeating/Init_TestProb_ELBDM_DiskHeating.cpp
Agree.

2025-01-07 03:19 UTC, ChunYen-Chen commented
@hyschive Thanks for the review. I have addressed the comment. Please take another review.

2025-01-12 10:54 UTC, hyschive commented
@ChunYen-Chen  I encountered the following error messages when using `gamer_compare_data` with the old data format, for both HDF5 and C-binary formats:
```
CompareParticleData ...
********************************************************************************
ERROR : particle integer arrays have not been allocated yet !!
        Rank <0>, file <Main.cpp>, line <439>, function <CompareParticleData>
********************************************************************************
```
I suspect the issue arises because `Aux_AllocateArray2D()` returns `NULL` when the array size is zero.

2025-01-14 02:05 UTC, hyschive requested changes
@ChunYen-Chen I've added some final minor comments, including a few bug fixes. Please also resolve the conflicts.

2025-01-14 08:35 UTC, hyschive commented on doc/wiki/Particles.md
> +* #### `PAR_IC_INT8` &ensp; (<0: same as [[--long_par | Installation:-Option-List#--long_par]], 0=single precision, 1=double precision) &ensp; [-1]
@ChunYen-Chen This hasn't been addressed

2025-01-14 08:40 UTC, ChunYen-Chen commented on doc/wiki/Particles.md
> +* #### `PAR_IC_INT8` &ensp; (<0: same as [[--long_par | Installation:-Option-List#--long_par]], 0=single precision, 1=double precision) &ensp; [-1]
The text is updated in `doc/wiki/Runtime-Parameters-related/Runtime-Parameters:-Particles.md`. I forgot to resolve the conversation.

2025-01-14 08:47 UTC, hyschive approved these changes

2025-01-14 08:48 UTC, merged