Add particle unique ID
gamer-project/gamer pull request #351
Opened 2024-09-09 06:08 UTC by ChunYen-Chen

This is a follow-up PR of PR #348. It solves part of #79.

# Changes
* Wiki pages about particles are updated.

# New
* A new built-in particle attribute `PAR_PUID` to store the particle UID.
* A new section of Wiki pages about particle UID.
* A new script `track_particle.py` to track the particle by UID.

# Results
### Comparison of tracking particle by UID and index of the array with different MPI rank number
Here I show the results of three different UIDs (`300`, `5403`, and `31111`) with different MPI ranks (`1`, `2`, and `16`). As shown in the figures, the particles can be tracked well by the UID.
![particle_00300](https://github.com/user-attachments/assets/f08b0b1e-e309-4476-b4ad-1b1f1f3c49e3)
![particle_05403](https://github.com/user-attachments/assets/ee14a1f7-dc22-4587-8eb1-1e4bd95b3158)
![particle_31111](https://github.com/user-attachments/assets/e7e574bf-e69d-49dd-87e4-4b05b84eb4a7)\
The figure shows the position and the velocity in each direction of particles with specified UID. The `idx` means the index of specified particle UID in the array at step 0.

# Note
* `yt` module does not recognize the integer attribute type correctly.
* `gamer_compare_data` is not supported yet.
* `libyt` is also not supported yet.

2025-11-15 10:41 UTC, hsinhaoHHuang requested changes
Hi @ChunYen-Chen,
I have quickly reviewed this PR. Please let me know if any of my comments are not clear. Thanks!

Besides, I have two questions regarding the initialization.
1. How does this unique ID work with `Par_Init_ByFile()`?
   - Do we expect to read the PUID from `PAR_IC`? Currently, it will try to read it. But if there is no PUID in `PAR_IC`, we may want to skip reading it and set it as `-1` by default. If there are already PUIDs in `PAR_IC`, how do we check them and set the `NextUID` correctly?
   - For example, the test problem `CDM_LSS` cannot work now
```
********************************************************************************
ERROR : size of the file <PAR_IC> = 75497472 != expect = 92274688 !!
        Rank <0>, file <Particle/Par_Init_ByFile.cpp>, line <113>, function <Par_Init_ByFile_Default>
********************************************************************************
```
2. How does this unique ID work with `Init_ByRestart()`?
   - If we try to restart from a snapshot without PUID, I guess it will fail because one attribute is missing. Does it mean we no longer support restarting particle simulations from the previous version? Or should we set a new PUID if there is none?

2025-11-15 10:41 UTC, hsinhaoHHuang commented on src/Particle/Par_Aux_InitCheck.cpp
> +         Aux_Error( ERROR_INFO, "PUid[%ld] = %ld (accepted range: 0<index<=%ld) !!\n", ParID, (long)PUid[ParID], amr->Par->NextUID );
Is it `(accepted range: 0<index<%ld)`?

2025-11-15 10:41 UTC, hsinhaoHHuang commented on src/Particle/Par_Aux_InitCheck.cpp
> +   MPI_Allreduce( &amr->Par->NPar_AcPlusInac, &NPar_AllRank, 1, MPI_LONG, MPI_SUM, MPI_COMM_WORLD );
It seems to me that `NPar_AllRank` is not used.

2025-11-15 10:41 UTC, hsinhaoHHuang commented on src/Particle/Par_Init_ByFunction.cpp
Should we add `ParPUid[p] = (long_par)-1;` in this template?

2025-11-15 10:41 UTC, hsinhaoHHuang commented on src/Particle/Par_Aux_Check_Particle.cpp
> +         Aux_Message( stderr, "Check 9: lv %d, PID %d, NPar_Copy = %d != -1 !!\n",
Should it be `Check 10`?

2025-11-15 10:41 UTC, hsinhaoHHuang commented on src/Particle/Par_Aux_Check_Particle.cpp
> +void Check_NPar_Active( int &PassAll, int &PassOne, const char *comment )
Would you think renaming it as something like `Check_NPar_Active_AllLv` or `Check_NPar_Lv` better (to distinguish it from the `Check_NPar_Active_AllRank` above)?

2025-11-15 10:41 UTC, hsinhaoHHuang commented on src/Particle/Par_Aux_Check_Particle.cpp
> +      if ( amr->Par->Mass[p] < (long_par)0.0 )   continue;
Is this to exclude the inactive particles? I thought inactive particles also have a UID. And why does it use `long_par` for `0.0`?

2025-11-15 10:41 UTC, hsinhaoHHuang commented on src/Particle/Par_Aux_Check_Particle.cpp
> +
The spacing here is different from the one in `Check_ValidUID()`.

2025-11-15 10:41 UTC, hsinhaoHHuang commented on src/Particle/Par_Aux_Check_Particle.cpp
> +   int    *Par_UID = new int [amr->Par->NextUID];
In my opinion, the name `Par_UID` is a little confusing. It is not an array of UID, but it is an array of the counted number of particles for each UID. Would you think adding `Num` into the variable name would be more descriptive?

2025-11-15 10:41 UTC, hsinhaoHHuang commented on src/Particle/Par_SetParUID.cpp
> +      for (int r=1; r<MPI_NRank; r++)  SendDisp[r] = SendDisp[r-1] + NSend[r-1];
Just curious, why is this written differently from the `if ( init )` part using `MPI_Gather`?

2025-11-15 10:41 UTC, hsinhaoHHuang commented on src/Particle/Par_SetParUID.cpp
> +         if ( amr->Par->PUid[p] != (long_par)-1 )   continue;
It seems it assumes the new particles are set with `PUid = -1`. This relies on the correct initialization in the star formation routines. Should we add a sanity check about it in this function? Maybe some particles have other invalid PUids (e.g., -2) accidentally.

2025-11-15 10:41 UTC, hsinhaoHHuang commented on src/Particle/Par_SetParUID.cpp
> +// Paramter    :  init : Initialization stage or not
I am wondering what the reason is to distinguish whether it is the initialization stage or not.
It seems to me that the non-initial mode is a more general method, and it can be applied to the initial mode.

And although in the current usage of `Par_Init_ByFunction_*()` the particle data are all constructed and scattered out by Rank-0, it seems to me there is no restriction for each MPI rank to construct its own particles in there (see Note 3.), and the order of particles among ranks may depend on the number of ranks and differ from the orders here.
Therefore, I think it will be safer to sort the particles by position before assigning their UID, as it is done in the non-initial mode.

2025-11-15 10:41 UTC, hsinhaoHHuang commented on src/Particle/Par_SetParUID.cpp
> +      amr->Par->NextUID += (long_par)NNewPar_AllRank;
Do you think we should check whether the `amr->Par->PUid` and `amr->Par->NextUID` will overflow before the addition? It seems the `long_par` is still a user's option, and it could be `int`.

2025-12-25 03:21 UTC, hsinhaoHHuang commented
Hi @ChunYen-Chen, I have just filed a [PR](https://github.com/ChunYen-Chen/gamer-fork/pull/9) to your branch to resolve my own comments and fix the reported issues about the restart. Please review it when you have time and let me know if there is anything that needs to be changed. Thanks a lot!

@hyschive After my changes are merged, I think this PR will need a third reviewer.

2026-01-05 11:47 UTC, hsinhaoHHuang approved these changes

2026-03-14 08:07 UTC, hyschive commented
@hsinhaoHHuang Since you have approved this PR, I assume all the remaining conversions have been addressed, right?

@ChunYen-Chen If so, please resolve the remaining conflicts and conservations. I'll then take a final look before merging it.

2026-03-14 08:56 UTC, hsinhaoHHuang commented
Yes, all my previous comments here should have been resolved by my changes.

2026-03-15 06:33 UTC, ChunYen-Chen commented
@hyschive I have updated the PR.
@hsinhaoHHuang Thanks for the quick response!

2026-03-17 12:15 UTC, barrytchiang commented on doc/wiki/Runtime-Parameters-related/[Runtime-Parameters]-Particles.md
> +[PAR_INIT](#PAR_INIT)=3. Note that when the particle initial condition file `PAR_IC`
```suggestion
Check whether all existing particles have UIDs assigned when [PAR_INIT](#PAR_INIT)=3 is used. Note that when the particle initial condition file `PAR_IC`
```

2026-03-17 12:17 UTC, barrytchiang commented on doc/wiki/Runtime-Parameters-related/[Runtime-Parameters]-Particles.md
> +one should turn this off and the new particle UID will be assigned internally.
```suggestion
one should turn this off and the new particle UIDs will be assigned internally.
```

2026-03-17 12:18 UTC, barrytchiang commented on doc/wiki/Runtime-Parameters-related/[Runtime-Parameters]-Particles.md
> +UID to `-1` then call `Par_SetUID(false)` to assign UID after all creations
```suggestion
UID to `-1` and then call `Par_SetUID(false)` to assign UID after all creations
```

2026-03-17 12:21 UTC, barrytchiang commented on doc/wiki/Runtime-Parameters-related/[Runtime-Parameters]-Particles.md
> +The particle UID is assigned by the following two situations:
```suggestion
The particle UID is assigned in only the following two situations:
```

2026-03-17 12:25 UTC, barrytchiang commented on doc/wiki/Initial-Conditions.md
> +to assign new particle UID to all particles when the file `PAR_IC` does not store existing particle UID.
```suggestion
to assign new particle UIDs to all particles when the `PAR_IC` file does not store existing UIDs.
```

2026-03-17 12:26 UTC, barrytchiang commented on example/test_problem/Hydro/CDM_LSS/Input__Parameter
> +PAR_IC_PUID                   0           # whether there are particle UID of all particles in the file for PAR_INIT==3 [0]
```suggestion
PAR_IC_PUID                   0           # whether all particles in the file have existing particle UIDs for PAR_INIT==3 [0]
```

2026-03-17 12:27 UTC, barrytchiang commented on example/test_problem/Template/Input__Parameter
> +PAR_IC_PUID                   0           # whether there are particle UID of all particles in the file for PAR_INIT==3 [0]
```suggestion
PAR_IC_PUID                   0           # whether all particles in the file have existing particle UIDs for PAR_INIT==3 [0]
```

2026-03-17 12:30 UTC, barrytchiang commented on src/Init/Init_GAMER.cpp
> +// assign initial particle UID AFTER all the routines possibly adding particles,
```suggestion
// assign initial particle UIDs AFTER all routines that possibly add particles,
```

2026-03-17 12:32 UTC, barrytchiang commented on src/Particle/Par_Aux_Check_Particle.cpp
> +// Parameter   :  PassAll    : Pass all the checkes or not
```suggestion
// Parameter   :  PassAll    : Pass all the checks or not
```

2026-03-17 12:32 UTC, barrytchiang commented on src/Particle/Par_Aux_Check_Particle.cpp
> +// Parameter   :  PassAll       : Pass all the checkes or not
```suggestion
// Parameter   :  PassAll       : Pass all the checks or not
```

2026-03-17 12:33 UTC, barrytchiang commented on src/Particle/Par_Aux_Check_Particle.cpp
> +// Parameter   :  PassAll : Pass all the checkes or not
```suggestion
// Parameter   :  PassAll : Pass all the checks or not
```

2026-03-17 12:33 UTC, barrytchiang commented on src/Particle/Par_Aux_Check_Particle.cpp
> +// Parameter   :  PassAll : Pass all the checkes or not
```suggestion
// Parameter   :  PassAll : Pass all the checks or not
```

2026-03-17 12:33 UTC, barrytchiang commented on src/Particle/Par_Aux_Check_Particle.cpp
> +// Parameter   :  PassAll : Pass all the checkes or not
```suggestion
// Parameter   :  PassAll : Pass all the checks or not
```

2026-03-17 12:33 UTC, barrytchiang commented on src/Particle/Par_Aux_Check_Particle.cpp
> +// Parameter   :  PassAll : Pass all the checkes or not
```suggestion
// Parameter   :  PassAll : Pass all the checks or not
```

2026-03-17 12:33 UTC, barrytchiang commented on src/Particle/Par_Aux_Check_Particle.cpp
> +// Parameter   :  PassAll : Pass all the checkes or not
```suggestion
// Parameter   :  PassAll : Pass all the checks or not
```

2026-03-17 12:33 UTC, barrytchiang commented on src/Particle/Par_Aux_Check_Particle.cpp
> +// Parameter   :  PassAll                    : Pass all the checkes or not
```suggestion
// Parameter   :  PassAll                    : Pass all the checks or not
```

2026-03-17 12:33 UTC, barrytchiang commented on src/Particle/Par_Aux_Check_Particle.cpp
> +// Parameter   :  PassAll  : Pass all the checkes or not
```suggestion
// Parameter   :  PassAll  : Pass all the checks or not
```

2026-03-17 12:33 UTC, barrytchiang commented on src/Particle/Par_Aux_Check_Particle.cpp
> +// Parameter   :  PassAll  : Pass all the checkes or not
```suggestion
// Parameter   :  PassAll  : Pass all the checks or not
```

2026-03-17 12:34 UTC, barrytchiang commented on src/Particle/Par_Aux_Check_Particle.cpp
> +// Parameter   :  PassAll : Pass all the checkes or not
```suggestion
// Parameter   :  PassAll : Pass all the checks or not
```

2026-03-17 12:34 UTC, barrytchiang commented on src/Particle/Par_Aux_Check_Particle.cpp
> +// Parameter   :  PassAll  : Pass all the checkes or not
```suggestion
// Parameter   :  PassAll  : Pass all the checks or not
```

2026-03-17 12:34 UTC, barrytchiang commented on src/Particle/Par_Aux_Check_Particle.cpp
> +// Parameter   :  PassAll      : Pass all the checkes or not
```suggestion
// Parameter   :  PassAll      : Pass all the checks or not
```

2026-03-17 12:35 UTC, barrytchiang commented on src/Particle/Par_Aux_Check_Particle.cpp
> +//                NParThisPatch : Number of particle in target patch
```suggestion
//                NParThisPatch : Number of particles in target patch
```

2026-03-17 12:38 UTC, barrytchiang commented on src/Particle/Par_Aux_Check_Particle.cpp
> +// Description :  Check if particle has unique UID
```suggestion
// Description :  Check if particles have unique UIDs
```

2026-03-17 12:39 UTC, barrytchiang commented on src/Particle/Par_Aux_InitCheck.cpp
> +//                6. Check particle ID (which can be not assigned yet when calling this function)
```suggestion
//                6. Check particle ID (which might not be assigned yet when calling this function)
```

2026-03-17 12:41 UTC, barrytchiang commented on src/Particle/Par_SetParUID.cpp
> +//                2. The new particle UID should be initialized as PPUID_TBA
```suggestion
//                2. New particle UIDs should be initialized as PPUID_TBA
```

2026-03-17 12:41 UTC, barrytchiang commented on src/Particle/Par_SetParUID.cpp
> +//                3. Currently, the new particles UID are given by the sorted position
```suggestion
//                3. Currently, new particle UIDs are assigned by the sorted particle position
```

2026-03-17 12:42 UTC, barrytchiang commented on src/Particle/Par_SetParUID.cpp
> +      if ( amr->Par->PUid[p] > (long_par)0  &&  amr->Par->PUid[p] < amr->Par->NextUID )   continue;  // exclude particles that already have valid UID
```suggestion
      if ( amr->Par->PUid[p] > (long_par)0  &&  amr->Par->PUid[p] < amr->Par->NextUID )   continue;  // exclude particles that already have valid UIDs
```

2026-03-17 12:49 UTC, barrytchiang reviewed
The PR looks good! I just left some small suggestions for grammar and clarity in the comments. One question I have is whether tracer particles (including those spawn on-the-fly) would be handled in the same "UID assignment pipeline", say in a simulation set up with star formation also enabled. This user case wasn't explicitly defined [here](https://github.com/gamer-project/gamer/pull/351/changes#diff-81369bfa312cb81e32a235bd86e09ca3262836496f7035f8955ae4d0c9e4d8cfR192). I would assume the tracer particles are handled in the same way as [the pipeline](https://github.com/gamer-project/gamer/pull/351/changes#diff-52a1d7af8a65174c53a419286120e11fc90ed00469c3b9384b94c13ea187febbR41) only excludes inactive particles (those with negative mass).

2026-03-23 15:07 UTC, hyschive requested changes
@ChunYen-Chen This PR is neat! I didn't expect it to be an easy task, but you have made the implementation look very straightforward.

I only have some minor comments. I would be happy to merge this PR once they are addressed. Please also check the following general comments:

- [x] This PR seems to use several variants of the term “particle UID”, for example, `ParICPUid, PUid, NextUID, PAR_PUID, PPUID_TBA, ParPUid`. How about adopting a more consistent naming scheme, for example
  - `ParICPUID, PUID, NextPUID, PAR_PUID, PUID_TBA, ParPUID` or
  - `ParICUID,UID, NextUID, PAR_UID, PUID_TBA, ParUID`?
- [ ] You mentioned the following unfinished tasks [here](https://github.com/gamer-project/gamer/pull/351#issue-2512997530). But I thought both tools now support integer particle attributes. Could you clarify?
  - `gamer_compare_data` is not supported yet.
  - `libyt` is also not supported yet.
- [ ] Please also take a look at the TODO list in #79.
  - [ ] Is there anything to add?
  - [ ] Is there anything marked unfinished that is already complete?

2026-03-23 15:07 UTC, hyschive commented on include/Particle.h
> +//                NextUID                 : Next new particle UID over all MPI ranks. The UID starts from 1.
Just curious. Why does it start from 1 rather than 0?

2026-03-23 15:07 UTC, hyschive commented on include/Particle.h
>  //                AttributeInt            : Pointer arrays to different particle integer        attributes (Type)
```suggestion
//                AttributeInt            : Pointer arrays to different particle integer        attributes (Type, PUid)
```

2026-03-23 15:07 UTC, hyschive commented on include/Particle.h
> +           ( NewAttInt[PAR_PUID] <= (long_par)0  ||  NewAttInt[PAR_PUID] >= NextUID ) )
I'm a bit confused by this check. Why must it lie within `0 < NewAttInt[PAR_PUID] < NextUID`? Naively, I would have thought it should simply be `NextUID` if we ever want to assign UID directly via `AddOneParticle()`.

2026-03-23 15:07 UTC, hyschive commented on include/Macro.h
> +#  define  PPUID_TBA                (long_par)-1
How about the following simplification? Please feel free to reject this suggestion if you think it’s not appropriate. Also check my general comments on this PR about variants of the term “particle UID”
```suggestion
// particle uid to be assigned
#  define  PUID_TBA                 (long_par)-1
```

2026-03-23 15:07 UTC, hyschive commented on example/test_problem/Hydro/ParticleTest/README
> +8. Use python script "track_particle.py" to track the position and velocity
```suggestion
8. Use the python script "track_particle.py" to track the position and velocity
```

2026-03-23 15:07 UTC, hyschive commented on src/StarFormation/SF_CreateStar_AGORA.cpp
> +//                   routine
```suggestion
//                5. The new particle UID should be initialized as PPUID_TBA. The actual UID will be assigned later in SF_CreateStar()
```

2026-03-23 15:07 UTC, hyschive commented on src/StarFormation/SF_CreateStar.cpp
> +//                3. Assign the new particles UID at the end of the routine
```suggestion
//                3. Assign UIDs to new particles at the end of this routine
```

2026-03-23 15:07 UTC, hyschive commented on src/StarFormation/SF_CreateStar.cpp
> +// set new UID for the new particles
```suggestion
// assign UIDs for new particles
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_SetParUID.cpp
> +//                3. Currently, new particle UIDs are assigned by the sorted particle position
```suggestion
//                2. New particle UIDs should be initialized to PPUID_TBA before calling this routine
//                   --> This routine only assigns UIDs to particles with UID==PPUID_TBA; other particles are skipped
//                3. Particle UIDs are assigned according to the sorted particle position
//                   --> Ensure reproducibility
```

2026-03-23 15:07 UTC, hyschive commented on src/Init/Init_GAMER.cpp
> +//           Par_AddParticleAfterInit() in Init_User_Ptr() and Init_User_AfterPoisson_Ptr()
```suggestion
// including Par_Init_ByFunction_Ptr(), Par_Init_ByFile(), AddParticle() in Init_ByRestart(), and
//           Par_AddParticleAfterInit() in Init_User_Ptr() and Init_User_AfterPoisson_Ptr()
```

2026-03-23 15:07 UTC, hyschive commented on src/Init/Init_GAMER.cpp
> +// assign initial particle UIDs AFTER all routines that possibly add particles,
```suggestion
// assign initial particle UIDs AFTER all routines that may add particles,
```

2026-03-23 15:07 UTC, hyschive commented on src/Init/Init_GAMER.cpp
> +// only check here if it will not check later in Aux_Check()
```suggestion
// only perform this check here if it will not be checked later in Aux_Check()
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_SetParUID.cpp
> +// Paramter    :  init : Initialization stage or not
It appears that this parameter is only for printing additional information during initialization. If so, I suggest removing this parameter and printing `"Par_SetParID (init) ...` directly in `Init_GAMER()`.

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_SetParUID.cpp
> +   MPI_Barrier( MPI_COMM_WORLD );
What's the purpose of adding this MPI barrier? It seems unnecessary to me.

If it is indeed necessary, add a comment to clarify its purpose. Otherwise, consider removing it.

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_SetParUID.cpp
> +      Aux_Error( ERROR_INFO, "amr->Par->NextUID(%ld) is invalid !!\n", amr->Par->NextUID );
```suggestion
      Aux_Error( ERROR_INFO, "amr->Par->NextUID (%ld) < 1 !!\n", amr->Par->NextUID );
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_SetParUID.cpp
> +// calculate number of new particles
```suggestion
// calculate the number of new particles
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_SetParUID.cpp
> +         Aux_Error( ERROR_INFO, "New particle before ParUID assignment has an invalid PUid[%ld] = %ld != %ld !!\n", p, (long)amr->Par->PUid[p], (long)PPUID_TBA );
```suggestion
         Aux_Error( ERROR_INFO, "New particle before UID assignment has an invalid PUid[%ld] = %ld != %ld !!\n",
                    p, (long)amr->Par->PUid[p], (long)PPUID_TBA );
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_SetParUID.cpp
> +      Aux_Error( ERROR_INFO, "NNewPar_AllRank(%ld) is negative !!\n", NNewPar_AllRank );
```suggestion
      Aux_Error( ERROR_INFO, "NNewPar_AllRank (%ld) is negative !!\n", NNewPar_AllRank );
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_SetParUID.cpp
> +   if ( NNewPar_AllRank <  0L )
```suggestion
   if ( NNewPar_AllRank < 0L )
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_SetParUID.cpp
> +   if ( amr->Par->NextUID >= ( (sizeof(long_par) == sizeof(int)) ? __INT_MAX__ : __LONG_MAX__ ) - NNewPar_AllRank )
Strictly speaking, I think the check should be ">" rather than ">=".
```suggestion
   if ( amr->Par->NextUID > ( (sizeof(long_par) == sizeof(int)) ? __INT_MAX__ : __LONG_MAX__ ) - NNewPar_AllRank )
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_SetParUID.cpp
> +      Aux_Error( ERROR_INFO, "amr->Par->PUid = amr->Par->NextUID(%ld) + NNewPar_AllRank(%ld) will overflow !!\n", amr->Par->NextUID, NNewPar_AllRank );
```suggestion
      Aux_Error( ERROR_INFO, "amr->Par->PUid = amr->Par->NextUID (%ld) + NNewPar_AllRank (%ld) - 1 will overflow !!\n", amr->Par->NextUID, NNewPar_AllRank );
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_SetParUID.cpp
> +      Aux_Error( ERROR_INFO, "NNewPar_ThisRank_int(%d) != NNewPar_ThisRank(%ld) !!\n", NNewPar_ThisRank_int, NNewPar_ThisRank );
```suggestion
      Aux_Error( ERROR_INFO, "NNewPar_ThisRank_int (%d) != NNewPar_ThisRank (%ld) !!\n", NNewPar_ThisRank_int, NNewPar_ThisRank );
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_SetParUID.cpp
> +      NewParPos_AllRank[d]  = new real_par [NNewPar_AllRank];
```suggestion
      NewParPos_AllRank [d]  = new real_par [NNewPar_AllRank];
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_SetParUID.cpp
> +      delete [] NewParPos_AllRank[d];
```suggestion
      delete [] NewParPos_AllRank [d];
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_SetParUID.cpp
> +// update the next UID to all ranks
```suggestion
// update the next UID on all ranks
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_Aux_Check_Particle.cpp
> +                         const int ParID, const real_par *ParPos[] )
Correct the other routines and all function prototypes at the top of this file as well. 
```suggestion
                         const long ParID, const real_par *ParPos[] )
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_Aux_Check_Particle.cpp
> +// Description :  Check if the particle reside in its home patch
```suggestion
// Description :  Check if the particle resides in its home patch
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_Aux_Check_Particle.cpp
> +                          const int ParID, double *EdgeL, double *EdgeR, const real_par *ParPos[] )
```suggestion
                          const int ParID, const double *EdgeL, const double *EdgeR, const real_par *ParPos[] )
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_Aux_Check_Particle.cpp
> +// Description :  Check if the inactive particle has negative mass
```suggestion
// Function    :  Check_InactiveParticle
// Description :  Check if amr->patch[0][lv][PID]->ParList[] contains any inactive particle
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_Aux_Check_Particle.cpp
> +                         const int ParID, const real_par *ParPos[] )
To be consistent with `amr->Par->Mass[ParID]`, how about using `amr->Par->PosX/Y/Z` directly rather than passing `ParPos[]`?

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_Aux_Check_Particle.cpp
> +// Description :  Check if the particle reside in the leaf patches
```suggestion
// Description :  Check if the particle resides in the leaf patch
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_Aux_Check_Particle.cpp
> +//                NParThisPatch : Number of particles in target patch
```suggestion
//                NParThisPatch : Number of particles in the target patch
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_Aux_Check_Particle.cpp
> +// Description :  Check if the active particle has only one home patch
```suggestion
// Description :  Check if the active particle has a home patch
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_Aux_Check_Particle.cpp
> +// Note        :  1. Must be executed after Check_OneHomePatch
```suggestion
// Note        :  1. Must be executed after Check_OneHomePatch()
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_Aux_Check_Particle.cpp
> +//                ParHome : Array of particle has home or not
```suggestion
//                ParHome : Array indicating whether each particle has a home patch
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_Aux_Check_Particle.cpp
> +//                ParHome : Array of particle has home or not
```suggestion
//                ParHome : Array indicating whether each particle has a home patch
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_Aux_Check_Particle.cpp
> +      if ( Par_CountUID[uid] <= 1 )   continue;
To be more specific.
```suggestion
      if ( Par_CountUID[uid] == 1 )   continue;
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_Aux_Check_Particle.cpp
> +         Aux_Message( stderr, "Check 13: %4s  %10s  %10s  %10s\n", "Rank", "ParUID", "Number", "NextUID" );
```suggestion
         Aux_Message( stderr, "Check 13: %4s  %10s  %10s  %10s\n", "Rank", "ParUID", "Count", "NextUID" );
```

2026-03-23 15:07 UTC, hyschive commented on src/Output/Output_DumpData_Total_HDF5.cpp
Update `FormatVersion` to `2506`

2026-03-23 15:07 UTC, hyschive commented on src/Init/Init_ByRestart_HDF5.cpp
> +   const bool isPUIDStored = KeyInfo.FormatVersion >= 2504;
```suggestion
   const bool isPUIDStored = KeyInfo.FormatVersion >= 2506;
```

2026-03-23 15:07 UTC, hyschive commented on src/Init/Init_ByRestart_HDF5.cpp
> +               if ( v == PAR_PUID  &&  !isPUIDStored )   continue;
How about setting `H5_SetID_ParIntData[v]` to `H5I_INVALID_HID`?

2026-03-23 15:07 UTC, hyschive commented on src/Init/Init_ByRestart_HDF5.cpp
> +   const bool isPUIDStored = FormatVersion >= 2504;
```suggestion
   const bool isPUIDStored = FormatVersion >= 2506;
```

2026-03-23 15:07 UTC, hyschive commented on src/Init/Init_ByRestart_HDF5.cpp
> +      const bool isPUIDStored = FormatVersion >= 2504;
```suggestion
      const bool isPUIDStored = FormatVersion >= 2506;
```

2026-03-23 15:07 UTC, hyschive commented on src/Init/Init_ByRestart_HDF5.cpp
> +         }
Integer particle data are not available prior to FormatVersion 2500. So how about simplifying it as follows?
```suggestion

         for (int p=0; p<NParThisPatch; p++)   ParIntBuf[PAR_PUID][p] = PPUID_TBA;
```

2026-03-23 15:07 UTC, hyschive commented on doc/wiki/Initial-Conditions.md
> +      ParPUid[p] = (long_par)-1;
```suggestion
      ParPUid[p] = PPUID_TBA;
```

2026-03-23 15:07 UTC, hyschive commented on src/Particle/Par_Init_ByFile.cpp
It seems that the following description is out-of-date. Do you agree?

@hsinhaoHHuang I wonder why #514 did not capture the typo "partice" below. 
```suggestion
//                7.  Load the following attributes with the specified order:
//
//                      mass, position x/y/z, velocity x/y/z,
//                      [, creation time (when enabling STAR_FORMATION)]
//                      [, user-specified floating-point attributes (when PAR_NATT_FLT_USER>0]
//                      , type, UID
//                      [, user-specified integer attributes (when PAR_NATT_INT_USER>0)]
//
//                   --> The mass of all particles can be set to PAR_IC_MASS instead (by having PAR_IC_MASS>=0.0),
//                       in which case PAR_IC should exclude particle mass
//                   --> The type of all particles can be set to PAR_IC_TYPE instead (by having PAR_IC_TYPE>=0),
//                       in which case PAR_IC should exclude particle type
//                   --> The UID of all particles can be excluded from PAR_IC by setting PAR_IC_PUID=0,
//                       in which case UID will be assigned automatically
```

2026-03-23 15:07 UTC, hyschive commented on doc/wiki/Initial-Conditions.md
> +type, UID, and user-specified attributes (and in exactly this order).
```suggestion
user-specified floating-point attributes, type, UID, and user-specified integer attributes (and in exactly this order).
```

2026-03-23 15:07 UTC, hyschive commented on doc/wiki/Initial-Conditions.md
> +to assign new particle UIDs to all particles when the `PAR_IC` file does not store existing UIDs.
```suggestion
to automatically assign new particle UIDs to all particles when the `PAR_IC` file does not contain UID information.
```

2026-03-23 15:07 UTC, hyschive commented on doc/wiki/Initial-Conditions.md
>        ParIC_Int[0][p] = 1;     // type (generic massive)
```suggestion
ParIC_Flt[0][p] = 1.1;                        // mass
ParIC_Flt[1][p] = 2.2;                        // position x
ParIC_Flt[2][p] = 3.3;                        // position y
ParIC_Flt[3][p] = 4.4;                        // position z
ParIC_Flt[4][p] = 5.5;                        // velocity x
ParIC_Flt[5][p] = 6.6;                        // velocity y
ParIC_Flt[6][p] = 7.7;                        // velocity z

 ParIC_Int[0][p] = PTYPE_GENERIC_MASSIVE;     // type (generic massive)
```

2026-03-23 15:07 UTC, hyschive commented on doc/wiki/Initial-Conditions.md
> +      ParIC_Int[1][p] = p+1;   // UID
```suggestion
      ParIC_Int[1][p] = p+1;                        // UID (starting from 1)
```

2026-03-23 15:07 UTC, hyschive commented on doc/wiki/Runtime-Parameters-related/[Runtime-Parameters]-Particles.md
> +one should turn this off and the new particle UIDs will be assigned internally.
```suggestion
Flag indicating whether the particle initial condition file `PAR_IC` contains UID information.
If this option is disabled, new particle UIDs will be assigned automatically.
```

2026-03-23 15:07 UTC, hyschive commented on doc/wiki/Runtime-Parameters-related/[Runtime-Parameters]-Particles.md
> +are done in a single routine.
```suggestion
Valid particle UIDs should lie within `[1, number of particles]`. If new particles are created
during the simulation, please assign their UIDs to `PPUID_TBA`, and then call `Par_SetUID()`
to assign UIDs after all particle creation within the same routine is complete.
```

2026-03-23 15:07 UTC, hyschive commented on doc/wiki/Runtime-Parameters-related/[Runtime-Parameters]-Particles.md
> +The particle UID is assigned in only the following two situations:
```suggestion
The particle UID is assigned only in the following two situations:
```

2026-03-23 15:07 UTC, hyschive commented on doc/wiki/Runtime-Parameters-related/[Runtime-Parameters]-Particles.md
> +   Finally, send the new particle UIDs back to all ranks.
```suggestion
1. Initialization

   Particle UIDs are assigned after `Par_Init_ByFunction_Ptr()` or `Par_Init_ByFile()`.
   First, we collect the particle UIDs from all ranks into a single array.
   Second, we assign the particle UIDs according to the array index plus one.
   Finally, send the particle UIDs back to all ranks.
2. During simulation

   Particle UIDs should be assigned _after_ all the particle creation within a
   single routine is complete (e.g. star formation).
   First, we collect the UIDs and positions of new particles from all ranks
   into a single array.
   Second, we sort the particles by their positions.
   Third, assign the particle UIDs according to the array index plus `NextUID`.
   Finally, send the new particle UIDs back to all ranks.
```

2026-03-23 15:07 UTC, hyschive commented on doc/wiki/Runtime-Parameters-related/[Runtime-Parameters]-Particles.md
> +> 2. The index of particle array in each rank.
I'm not sure whether we should specify this, since the results may depend on how the sorting is implemented. What do you think?

2026-03-23 15:07 UTC, hyschive commented on doc/wiki/Runtime-Parameters-related/[Runtime-Parameters]-Particles.md
> +> If the particle positions are exactly the same (which should unlikely happen), the UID is decremented by the following order:
```suggestion
> If the particle positions are exactly the same (which should unlikely happen), the UID is determined by the following order:
```

2026-03-23 15:07 UTC, hyschive commented on example/test_problem/Hydro/ParticleTest/track_particle.py
> +                     help='Use Data_* to analysis (slower)' )
```suggestion
                     help='Use Data_* for analysis (slower)' )
```

2026-03-23 15:07 UTC, hyschive commented on example/test_problem/Hydro/ParticleTest/track_particle.py
> +parser = argparse.ArgumentParser( description='Plot the particles position and velocity by UID and array index' )
```suggestion
parser = argparse.ArgumentParser( description='Plot the particle positions and velocities by particle UIDs and array indices' )
```

2026-03-23 15:07 UTC, hyschive commented on example/test_problem/Hydro/ParticleTest/track_particle.py
> +parser.add_argument( '-t', action='store_true', required=False, dest='use_hdf5',
How about enabling this option by default since `OPT__OUTPUT_PAR_MODE` is turned off by default?

2026-03-23 15:07 UTC, hyschive commented on example/test_problem/Hydro/ParticleTest/track_particle.py
It would be great if this script could also plot at least one of the fluid fields specified in `Input__Par_Mesh` that are mapped onto tracer particles. For example, the mapped `Dens` field is stored in `Data_*:Particle/MeshDens`.

It would be even better if the results could also be compared with the prescribed gas distribution. You could refer to the `comp_dens/pres/velx` routines in `check_mesh2tracer.py`.

Note that the mapped data are currently only stored in `Data_*` but not in `Particle_*`.

2026-03-23 15:07 UTC, hyschive requested changes
@ChunYen-Chen This PR is neat! I didn't expect it to be an easy task, but you have made the implementation look very straightforward.

I only have some minor comments. I would be happy to merge this PR once they are addressed. Please also check the following general comments:

- [ ] This PR seems to use several variants of the term “particle UID”, for example, `ParICPUid, PUid, NextUID, PAR_PUID, PPUID_TBA, ParPUid`. How about adopting a more consistent naming scheme, for example
  - `ParICPUID, PUID, NextPUID, PAR_PUID, PUID_TBA, ParPUID` or
  - `ParICUID,UID, NextUID, PAR_UID, PUID_TBA, ParUID`?
- [ ] You mentioned the following unfinished tasks [here](https://github.com/gamer-project/gamer/pull/351#issue-2512997530). But I thought both tools now support integer particle attributes. Could you clarify?
  - `gamer_compare_data` is not supported yet.
  - `libyt` is also not supported yet.
- [ ] Please also take a look at the TODO list in #79.
  - [ ] Is there anything to add the list?
  - [ ] Is there anything marked unfinished that is already complete?

2026-03-25 12:11 UTC, barrytchiang approved these changes
Aside from [this minor question I have about tracer particles ](https://github.com/gamer-project/gamer/pull/351#pullrequestreview-3960514623)(which is already taken care of based on my understanding), all looks good on my end!

2026-03-25 18:00 UTC, ChunYen-Chen commented on doc/wiki/Initial-Conditions.md
>        ParIC_Int[0][p] = 1;     // type (generic massive)
Do you mean to update only line 735?

2026-03-26 02:21 UTC, hyschive commented on doc/wiki/Initial-Conditions.md
>        ParIC_Int[0][p] = 1;     // type (generic massive)
@ChunYen-Chen No. My main intention is to replace `1` with `PTYPE_GENERIC_MASSIVE` at line 743. The changes on other lines are just for alignment.

I don't think the modification highlighting on GitHub works correctly when commenting on unchanged lines.

2026-03-26 02:23 UTC, hyschive commented on example/test_problem/Hydro/ParticleTest/track_particle.py
You could raise a warning if the specified particle is actually not a tracer particle (for which `Particle/MeshDens` will be set to `__FLT_MAX__`.

2026-04-09 06:07 UTC, ChunYen-Chen commented on src/Particle/Par_Init_ByFile.cpp
@hsinhaoHHuang

2026-04-09 08:30 UTC, hsinhaoHHuang commented on src/Particle/Par_Init_ByFile.cpp
I am not sure why this typo was missed by Codex. Maybe I didn't push Codex hard enough, or my prompting skills need to be improved.

Here is its excuse:
> I was using a heuristic typo-mining approach (custom misspelling lists + targeted regex), not a full dictionary spellchecker over all comments.
> 
> partice is a low-frequency, domain-context typo that slipped through because it wasn’t in my initial typo list patterns.
> 
> I also had to keep precision high (avoid flagging variable names / jargon), so my filters were conservative and let some real typos pass.

2026-04-09 08:52 UTC, hyschive commented on src/Particle/Par_Init_ByFile.cpp
@hsinhaoHHuang Got it. Thanks for the clarification.

2026-04-09 08:58 UTC, hsinhaoHHuang commented on include/Particle.h
> +           ( NewAttInt[PAR_PUID] <= (long_par)0  ||  NewAttInt[PAR_PUID] >= NextUID ) )
I thought this was to check if the particle's `PAR_PUID` is valid. A possible `PAR_PUID` can be either `PUID_TBA` (for new particles before `Par_SetParUID()` is invoked) or in the range `[1, NextUID-1]` (for existing particles).

2026-04-09 09:14 UTC, hyschive commented on include/Particle.h
> +           ( NewAttInt[PAR_PUID] <= (long_par)0  ||  NewAttInt[PAR_PUID] >= NextUID ) )
OK. I forgot that `AddOneParticle()` is also called when exchanging existing particles between MPI ranks.

Regarding the check `NewAttInt[PAR_PUID] >= NextUID`, when adding a new particle, can we directly assign its UID as `NextUID`, or must the UID be initialized to `PUID_TBA`? I understand that we currently always use `PUID_TBA`, but I'm wondering whether the design also intends to support assigning `NextUID` directly.

2026-04-09 09:44 UTC, hsinhaoHHuang commented on include/Particle.h
> +           ( NewAttInt[PAR_PUID] <= (long_par)0  ||  NewAttInt[PAR_PUID] >= NextUID ) )
I think we don't intend to determine a particle's UID in `AddOneParticle()`; we only copy it here.
The assignment of UID should be done in `Par_SetParUID()` to ensure its uniqueness, sortedness, and consistency among all ranks.

There are only two possibilities for a particle in `AddOneParticle()`:
1. `UID == PUID_TBA`: It is a new particle, and we hold its place and will wait for the next `Par_SetParUID()` to assign its UID.
2. `UID in [1, NextUID-1]`: It is an existing particle, and it is normal.

If a particle has `UID >= NextUID`, it means something wrong has happened (e.g., during its initialization, or during the assignment in `Par_SetParUID()`, or during updating `NextUID`).
- If it is really a new particle, `Par_SetParUID()` will fail to recognize it as a new particle to be assigned.
- Directly assigning its UID to `NextUID` in `AddOneParticle()` may cause conflicting UIDs between particles, as we don't update and synchronize the global `NextUID` in this function.

2026-04-09 09:50 UTC, hyschive commented on include/Particle.h
> +           ( NewAttInt[PAR_PUID] <= (long_par)0  ||  NewAttInt[PAR_PUID] >= NextUID ) )
OK. Clarify it somewhere in this PR and then close this conservation.

2026-04-09 11:14 UTC, hsinhaoHHuang commented on include/Particle.h
> +           ( NewAttInt[PAR_PUID] <= (long_par)0  ||  NewAttInt[PAR_PUID] >= NextUID ) )
@ChunYen-Chen Hi, since this is sort of a confusion I made, please let me know whether you would like to help me update it directly, or if you prefer I make it clearer by filing a PR to your repo. Thanks!

2026-04-10 23:18 UTC, ChunYen-Chen commented on include/Particle.h
> +           ( NewAttInt[PAR_PUID] <= (long_par)0  ||  NewAttInt[PAR_PUID] >= NextUID ) )
@hsinhaoHHuang It would be great if you could file a PR to my repository. Thanks for your help!

2026-04-10 23:31 UTC, ChunYen-Chen commented on include/Particle.h
> +//                NextUID                 : Next new particle UID over all MPI ranks. The UID starts from 1.
Some compilers initialize unassigned variables to `0`. If a user forgets to assign `PUID` to `PUID_TBA`, we can easily detect incorrect behavior by checking if `PUID < 1` . Although we do have `Check_UniquePUID` to verify uniqueness, it is not as efficient as this simple check.
If you would prefer `PUID` to start from `0`, I can update it.

2026-04-11 02:49 UTC, hyschive commented on include/Particle.h
> +//                NextUID                 : Next new particle UID over all MPI ranks. The UID starts from 1.
Thanks for the clarification. No need to update this starting value. However, it would be helpful to add a comment explaining the consideration mentioned above.

2026-04-11 05:58 UTC, hsinhaoHHuang commented on include/Particle.h
> +      if ( ( NewAttInt[PAR_PUID] != PUID_TBA )  &&
```suggestion

//    check whether the particle UID is valid
//    a particle here can be either newly created or pre-existing
//    --> newly created: must have particle UID == PUID_TBA
//                       since Par_SetParUID() has not yet assigned it;
//                       UID will not be decided here; the particle is added to the list 
//                       as PUID_TBA and assigned a proper UID later in Par_SetParUID()
//    --> pre-existing : the particle UID must have been assigned by Par_SetParUID() and
//                       lie within [1, NextPUID-1]
      if ( ( NewAttInt[PAR_PUID] != PUID_TBA )  &&
```

2026-04-11 05:58 UTC, hsinhaoHHuang commented on src/Particle/Par_Aux_InitCheck.cpp
> +      if ( PUid[ParID] != PUID_TBA  &&  ( PUid[ParID] <= 0  ||  PUid[ParID] >= amr->Par->NextPUID ) )
```suggestion
//    check particle UID
//    a particle here can be initialized via PAR_INIT_BY_FUNCTION or PAR_INIT_BY_FILE
//    --> if the particle UID is loaded by Par_Init_ByFile(),
//        it must lie within [1, NextPUID-1]
//    --> if it is not loaded from a file,
//        the initialized particle should not be assigned a new UID beforehand
//        and must have particle UID == PUID_TBA,
//        so that Par_SetParUID() can be invoked to assign it properly
      if ( PUid[ParID] != PUID_TBA  &&  ( PUid[ParID] <= 0  ||  PUid[ParID] >= amr->Par->NextPUID ) )
```

2026-04-11 05:58 UTC, hsinhaoHHuang commented on src/Particle/Par_Aux_InitCheck.cpp
> +//    --> also check particle types and ID here
```suggestion
//    --> also check particle types and UID here
```

2026-04-11 05:58 UTC, hsinhaoHHuang commented on doc/wiki/Runtime-Parameters-related/[Runtime-Parameters]-Particles.md
> +   Example: `src/StarFormation/SF_CreateStar.cpp` and `src/StarFormation/SF_CreateStar_AGORA.cpp`
```suggestion
Valid particle UIDs should lie within `[1, number of particles]`.

The particle UID assignment occurs during either initialization or on-the-fly creation 
in simulation (e.g., star formation). The particle UIDs can be inherited from `PAR_IC` 
(when `PAR_INIT=3` and `PAR_IC_PUID` is enabled) or from a restart file. Except for 
these, the particle UIDs should be assigned internally via `Par_SetParUID()` in all 
other cases (e.g., `PAR_INIT=1`).

To ensure uniqueness and reproducibility, all particle UIDs should be assigned by 
`Par_SetParUID()` globally, rather than decided by individual MPI ranks. The particle 
UID must be first marked as `PUID_TBA` when the particle is created (e.g., in 
`Par_Init_ByFunction_Ptr()`, `Par_Init_ByFile()`, 
`src/StarFormation/SF_CreateStar_AGORA.cpp`) before invoking `Par_SetParUID()` (e.g., at 
the end of `Init_GAMER()` and `SF_CreateStar()`). And `Par_SetParUID()` should be 
invoked _after_ all the particle creation within a single routine is complete.

The assignment procedure of `Par_SetParUID()` follows:

   First, we collect the PUIDs and positions of new particles from all ranks
   into a single array.
   Second, we sort the particles by their positions.
   Third, assign the particle UIDs according to the array index plus `NextPUID`.
   Finally, send the new particle UIDs back to all ranks.
```

2026-04-11 05:58 UTC, hsinhaoHHuang commented on include/Particle.h
> +           ( NewAttInt[PAR_PUID] <= (long_par)0  ||  NewAttInt[PAR_PUID] >= NextUID ) )
It occurs to me that I can simply use review suggestions.
I have updated some comments. Please help review them to see whether it is clear. Thank you!

2026-04-18 14:22 UTC, hyschive commented on src/Particle/Par_Init_ByFunction.cpp
> +      ParPUid[p] = PUID_TBA;
@ChunYen-Chen @hsinhaoHHuang IIUC, `ParPUid[]` should never be assigned directly by a test problem initializer (thus it should always be set to `PUID_TBA` here). In that case, would it make sense to simplify initialize it at the end of `amr->Par->InitRepo()` ([example](https://github.com/hyschive/gamer-fork/blob/pr-flag-par-target/include/Particle.h#L431-L435))?

Doing so would also eliminate the need to pass `ParPUid[]` into each `Par_Init_ByFunction_*`, making the code clearer and less error-prone by preventing users from incorrectly setting `ParPUid[p]`.

What do you think?

2026-04-19 04:18 UTC, hsinhaoHHuang commented on src/Particle/Par_Init_ByFunction.cpp
> +      ParPUid[p] = PUID_TBA;
I think it works. And I agree that eliminating `ParPUid` in `Par_Init_ByFunction_*` makes sense, especially since it's not allowed to be set there anyway.

One potential downside I can think of: this approach could create differences in how we initialize different particle attributes. And the tasks of functions `Par_Init_*` and `amr->Par->InitRepo()` might overlap and mix. Some attributes would be initialized in one place, while others are initialized elsewhere. This separates what might be conceptually related initialization logic. With the current approach, when I need to find where to set `ParPUid`, I simply look for where `ParType` is handled. This makes the codebase easier to navigate. We may lose that convenience if we split the initialization logic.

2026-04-20 03:17 UTC, hyschive commented on src/Particle/Par_Init_ByFunction.cpp
> +      ParPUid[p] = PUID_TBA;
Thanks for raising this concern. My view is that `amr->Par->InitRepo()` is responsible for assigning default values, whereas `Par_Init_*` handles user-specified values. These defaults can then be used either to validate that users have properly reset them (e.g., for `PAR_TYPE`; see below) or to identify particles that should be reassigned automatically later (e.g., for `PAR_PUID`).

Along the same line, we may consider also initializing the particle type to `PTYPE_TBA` (defined as `-1` in `Macro.h`) in `InitRepo()`.

To clarify, I’m not proposing that all particle attributes be initialized in `InitRepo()`. My primary goal is to simplify the `Par_Init_ByFunction_*()` interface, which is exposed to users.

2026-04-24 10:06 UTC, ChunYen-Chen commented on src/Particle/Par_Init_ByFunction.cpp
> +      ParPUid[p] = PUID_TBA;
@hsinhaoHHuang @hyschive Thanks for the detailed discussion.
Since `PUID` is a special attribute, how about separating the `ParPUid[]` assignment into a dedicated function pointer, `Par_Init_PUID_ptr`?
If the function pointer is not provided, all `PUID`s will be set to `PUID_TBA`, and then `Par_SetParUID()` will be executed.
If the function pointer is provided, users can assign `PUID`s themselves, and we will perform checks to ensure they do not violate any `PUID` rules.

2026-04-24 12:46 UTC, hyschive commented on src/Particle/Par_Init_ByFunction.cpp
> +      ParPUid[p] = PUID_TBA;
@ChunYen-Chen I would prefer not to add another function pointer. If we decide not to pass `ParPUid[]` into each `Par_Init_ByFunction_*` and users still want to assign `PUID` manually, they can set `AllAttributeInt[PAR_PUID]` directly.

Note that the reason we pass pointers like `ParMass` and `ParType` separately from `AllAttributeFlt[PAR_NATT_FLT_TOTAL]` and `AllAttributeInt[PAR_NATT_INT_TOTAL]` is simply to remind users that these attributes must be set here. This is also why I suggest removing the `ParPUid` parameter to avoid potential confusion.

So my suggestion is to either keep your current implementation or move the initialization of `PUID` to the end of `amr->Par->InitRepo()`. What do you think?

2026-04-24 13:07 UTC, hyschive commented
@ChunYen-Chen Since the C-binary output format is deprecated (i.e., `OPT__OUTPUT_TOTAL = 2`), I suggest the following changes:
- `Output_DumpData_Total.cpp`: update `FormatVersion` to `2310`.
- `Init_ByRestart_v2.cpp`: raise an error when `PARTICLE` is enabled and restarting from a file with `FormatVersion < 2310`.

Do you agree?

2026-04-25 05:34 UTC, hyschive commented on src/Init/Init_ByRestart_HDF5.cpp
> +   const bool isPUIDStored = KeyInfo.FormatVersion >= 2508;
Since `isPUIDStored` is used in multiple places, how about declaring it as a static global variable and assigning its value at the beginning of this routine?

2026-04-25 05:34 UTC, hyschive commented on src/Init/Init_ByRestart_HDF5.cpp
> +   if ( KeyInfo.FormatVersion >= 2500  &&  isPUIDStored )
How about simplifying it to `if ( isPUIDStored )`?

2026-04-25 05:34 UTC, hyschive commented on src/Init/Init_ByRestart_HDF5.cpp
> +   if ( FormatVersion >= 2500  &&  isPUIDStored )
How about simplifying it to `if ( isPUIDStored )`?

2026-04-25 07:39 UTC, hyschive commented on src/Init/Init_ByRestart_HDF5.cpp
> +   const bool isPUIDStored = KeyInfo.FormatVersion >= 2508;
You can refer to this [commit](https://github.com/hyschive/gamer-fork/commit/5df8b715574096d5f59fd3cc8bf6286481ca02fb), where I'm adding another particle integer attribute used to flag grids for refinement.

2026-04-29 07:04 UTC, ChunYen-Chen commented
> Since the C-binary output format is deprecated (i.e., `OPT__OUTPUT_TOTAL = 2`), I suggest the following changes:
`Output_DumpData_Total.cpp`: update `FormatVersion` to `2310`.
`Init_ByRestart_v2.cpp`: raise an error when `PARTICLE` is enabled and restarting from a file with `FormatVersion < 2310`.
Do you agree?

@hyschive I assume you are referring to version `2510`. If so, I have updated the relevant files.

2026-04-29 07:05 UTC, ChunYen-Chen commented on src/Particle/Par_Init_ByFunction.cpp
> +      ParPUid[p] = PUID_TBA;
@hyschive Sounds great! I will move the initialization of PUID to the end of `amr->Par->InitRepo()`.

2026-04-29 07:49 UTC, hyschive commented
> > Since the C-binary output format is deprecated (i.e., `OPT__OUTPUT_TOTAL = 2`), I suggest the following changes:
> > `Output_DumpData_Total.cpp`: update `FormatVersion` to `2310`.
> > `Init_ByRestart_v2.cpp`: raise an error when `PARTICLE` is enabled and restarting from a file with `FormatVersion < 2310`.
> > Do you agree?
> 
> @hyschive I assume you are referring to version `2510`. If so, I have updated the relevant files.

No, I mean `FormatVersion` in `Output_DumpData_Total.cpp` instead of `Output_DumpData_Total_HDF5.cpp`

2026-04-29 07:52 UTC, hyschive commented on src/Particle/Par_Init_ByFunction.cpp
> +      ParPUid[p] = PUID_TBA;
@ChunYen-Chen OK. You can follow this [example](https://github.com/hyschive/gamer-fork/blob/pr-flag-par-target/include/Particle.h#L431-L435) in my recent PR #520.

2026-05-11 07:04 UTC, ChunYen-Chen commented
@hyschive @hsinhaoHHuang @barrytchiang Thanks for the detailed review! I have updated the PR, and I think it is ready for another review.

@hyschive 
> You mentioned the following unfinished tasks https://github.com/gamer-project/gamer/pull/351#issue-2512997530. But I thought both tools now support integer particle attributes. Could you clarify?

Since #348 has been merged, both tools are now supported.

> Please also take a look at the TODO list in https://github.com/gamer-project/gamer/issues/79.
>  Is there anything to add the list?

No, I think that is all.
>  Is there anything marked unfinished that is already complete?

"Update `gamer_compare_data`" is completed.

2026-05-11 07:20 UTC, hyschive commented
@ChunYen-Chen Thanks for the update! I'll take a final check before merging as soon as possible.

2026-05-19 02:35 UTC, hyschive approved these changes
@ChunYen-Chen Great job! I will merge it right away!

I'll add a follow-up commit afterward to fix a few remaining minor issues.

2026-05-19 02:35 UTC, merged

2026-05-19 03:10 UTC, hyschive commented
A few minor updates have been applied afterward in commits 8121629b9f458d77239b66b51f75a2a591ecbd40 and a1735d44186301003c980c0dd9870af817807199.