Update simulation option on Wiki
gamer-project/gamer pull request #373
Opened 2024-11-17 06:22 UTC by ChunYen-Chen

* Remove all the editing instructions of the `Makefile`
* Update the simulation options with `configure.py` options
* Update libyt arguments
* Separate the developer guide of `configure.py` to a new page
* Move simulation options under `Installation: Generate Makefile` page

Resolve: #372

2024-11-17 14:06 UTC, hyschive commented on doc/wiki/Installation:-Generate-Makefile.md
> +      <td><b>GAMER Name</b></td>
This is only relevant for developers. So how about moving it to the last row and renaming it as `Corresponding symbolic constant`?

2024-12-11 02:10 UTC, ChunYen-Chen commented
@hyschive I have included the new options introduced by #376.

2024-12-20 14:59 UTC, hyschive requested changes
@ChunYen-Chen Looks great! I only have some minor comments. A few links do not work correctly.

2024-12-20 14:59 UTC, hyschive commented on doc/wiki/Installation:-Option-List.md
> +| `--eos`        | `GAMMA`, `ISOTHERMAL`, `COSMIC_RAY`, `TAUBMATHEWS`, `USER` | Depend  | [[Equation of state \| equation-of-state]] | The following options only support `GAMMA`: `--flu_scheme=RTVD/C
Currently, we only include links for a small subset of options (e.g., `--barotropic` here). To keep things simple, how about removing all `--XXX` links from this page, as they all refer to content already on the same page?

2024-12-20 14:59 UTC, hyschive commented on doc/wiki/Installation:-Option-List.md
> +| `--elbdm_scheme`     | `ELBDM_WAVE`, `ELBDM_HYBRID`                    | `ELBDM_WAVE`    | ELBDM schemes. `ELBDM_WAVE`: wave-only; `ELBDM_HYBRID`: fluid-wave-hybrid-scheme | Must set `--model=ELBDM
"fluid-wave hybrid scheme"

2024-12-20 14:59 UTC, hyschive commented on doc/wiki/Installation:-Option-List.md
> +| `--wave_scheme`      | `WAVE_FD`, `WAVE_GRAMFE`                        | `WAVE_FD`       | Wave schemes. `WAVE_FD`: finite difference; `WAVE_GRAMFE`: local spectral method | Must set `--model=ELBDM
"`WAVE_GRAMFE`: local pseudospectral method based on Fourier continuations with Gram polynomials (hereafter also referred to as the Gram-Fourier extension method; GramFE)"

2024-12-20 14:59 UTC, hyschive commented on doc/wiki/Installation:-Option-List.md
> +| `--conserve_mass`    | `true`, `false`                                 | `true`          | Enforce the mass conservation | Must set `--model=ELBDM` | <a name="--conserve_mass"></a> `CONSERVE_MASS`
"Enforce mass conservation"

2024-12-20 14:59 UTC, hyschive commented on doc/wiki/Installation:-Option-List.md
> +| `--laplacian_four`   | `true`, `false`                                 | Depend          | Enable the fourth-order Laplacian | Must set `--model=ELBDM` and `--wave_scheme=WAVE_FD` | <a name="--lapl
"Adopt the fourth-order Laplacian for `--wave_scheme=WAVE_FD`"

2024-12-20 14:59 UTC, hyschive commented on doc/wiki/Installation:-Option-List.md
> +| `--gramfe_scheme`    | `GRAMFE_MATMUL`, `GRAMFE_FFT`                   | `GRAMFE_MATMUL` | GramFE schemes. `GRAMFE_MATMUL`: faster for `PATCH_SIZE`=8; `GRAMFE_FFT`: faster for larger patch sizes |
- "`GRAMFE_MATMUL`: matrix-multiplication approach, which is faster for `PATCH_SIZE`=8; `GRAMFE_FFT`: FFT approach, which is faster for larger patch sizes"
- "Must set `--fftw` when using both `--gramfe_scheme=GRAMFE_FFT` and `--gpu=false` | <a name="--gramfe_scheme"></a> `GRAMFE_SCHEME`"

2024-12-20 14:59 UTC, hyschive commented on doc/wiki/Installation:-Option-List.md
> +| `--hybrid_scheme`    | `HYBRID_UPWIND`, `HYBRID_FROMM`, `HYBRID_MUSCL` | `HYBRID_MUSCL`  | Fluid schemes. `HYBRID_UPWIND`: first-order, diffusive; `HYBRID_FORMM`: second-order, no limiter, unstable
"Fluid schemes supported by the fluid-wave hybrid algorithm"

2024-12-20 14:59 UTC, hyschive commented on doc/wiki/Installation:-Option-List.md
> +-- see [[Hydro]] for the related runtime parameters and other settings
Add "; must enable `--model=HYDRO`" at the end of this sentence. Modify other similar descriptions below each section too.

2024-12-20 14:59 UTC, hyschive commented on doc/wiki/Installation:-Option-List.md
> +-- see [[ELBDM]] for the related runtime parameters and other settings
Add "; must enable --model=ELBDM" at the end of this sentence. Then you can remove "Must set `--model=ELBDM`" from the `Restriction` column.

2024-12-20 14:59 UTC, hyschive commented on doc/wiki/Installation:-Option-List.md
> +| `--gpu`         | `true`, `false` | `false` | Enable GPU acceleration | Must specify `GPU_COMPUTE_CAPABILITY` in configuration file as well; may need to set `CUDA_PATH` in [[configuration file \| I
Change to "Must specify GPU_COMPUTE_CAPABILITY and may need to set CUDA_PATH in configuration file"

2024-12-20 14:59 UTC, hyschive commented on doc/wiki/Installation:-Option-List.md
> +| `--rng`                     | `RNG_GNU_EXT`, `RNG_CPP11` | `RNG_GNU_EXT` | Random number generators. `RNG_GNU_EXT`: GNU extension `drand48_r`; `RNG_CPP11`: c++11 `&lt;random&gt;` | Use `RNG_GNU_EXT
- It displays as `&lt;random&gt;` instead of `<random>`

2024-12-21 08:34 UTC, hyschive approved these changes
Everything looks good!

2024-12-21 08:34 UTC, merged