Add Default Machine Setting
gamer-project/gamer pull request #383
Opened 2024-12-05 15:14 UTC by technic960183

## Summary
This PR introduces a mechanism to specify default machine settings at both the repository and user levels, enhancing flexibility and usability in configuring the `--machine` argument for `configure.py`.

## Rationale
This design mirrors common configuration practices used by tools such as `git`, `vim`, and `yt`, offering flexibility with multiple levels of configuration. The repository-level setting provides a tailored environment for specific projects (as @ChunYen-Chen ask for), while the user-level setting allows global defaults (as @hyschive ask for).

## Features Added
Two Levels of Default Settings:

**Repository-Level** (`.local_settings`): Located in `src/.local_settings` to specify default settings for a specific repository.
**User-Level** (`global_settings`): Stored in `$HOME/.config/gamer/global_settings`, serving as a global fallback when repository-level settings are absent.

The name of the setting files are not `.gamerrc` because this is not a "rc" (runtime configuration) for Gamer.

### Backward compatibility
The default machine is determined in the following order:
- Explicit argument passed to `configure.py`.
- Repository-level local settings.
- User-level global settings.
- Fallback to `eureka_intel`.

## Files Changed

### Changes in `src/configure.py`

- The default of `--machine` flag is now `None`.
- Added `get_machine()` function to retrieve the machine setting from the new default configuration system.
- Raises a `FileNotFoundError` if the `.config` files are not found.

### Add Setup Script `tool/setup.sh`
A new script `tool/setup.sh` is provided to help users set the default machine during the initial setup.
This script clarifies its one-time usage for defining defaults.

### Updated `.gitignore`
Added `src/.local_settings` to `.gitignore` to avoid tracking repository-level configuration files.

### Removal of Hardcoded Defaults in `generate_make.sh`
Removed hardcoded `--machine=eureka_intel` in these scripts, ensuring that the new hierarchical default mechanism is utilized.

2024-12-12 09:40 UTC, technic960183 commented
Rebasing and force-pushing updated for including change of #376 .
Will wait #373 to merge for updating the Wiki.

2024-12-27 16:29 UTC, ChunYen-Chen requested changes
@technic960183 Thanks for the contribution. I have left some comments. There are some typos and a bug that need to be fixed. The rest of the comments are optimization and improving maintainability. Let me know if you have better ideas, or we can discuss it at the lab.

2024-12-27 16:29 UTC, ChunYen-Chen commented on doc/wiki/Installation:-Option-List.md
> +| `--machine` | Filename string | Select the `*.config` file from the `configs` directory. It will overwrite the default settings. |
You might also want to mention about the setting files.

2025-01-08 16:19 UTC, technic960183 reviewed
Thanks for the code review. I learned a lot.

I have mark some trivial or not-plain-to-fix comments as resolved.
And those unresolved are the one that need you to take a look.

Still, because the renaming of nearly all of the relevant files. Please start new comments on the renamed file. And I'll resolve the comments which you approved or have a corresponding new comment.

2025-01-08 16:19 UTC, technic960183 commented on src/configure.py
> +        raise BaseException("Python 3.5 or later is required.")
Add Python version checking to avoid [`typing`](https://docs.python.org/3/library/typing.html) causing problem.

Python 3.4 has ended its life nearly 6 years ago (since 2019-03-18). I think it will be fine for us to not support Python 3.4 and lower.
Ref: https://devguide.python.org/versions/

2025-01-14 11:14 UTC, ChunYen-Chen requested changes

2025-01-14 11:14 UTC, ChunYen-Chen commented on doc/wiki/Installation.md
> +   Furthermore, you can override the default setting with the `--machine=` [[option | Installation:-Option-List]] in `configure.py`.
```suggestion
   Furthermore, you can override the default setting by passing the [[--machine | Installation:-Option-List#--machine]]=`your_machine` when executing `configure.py`. 
```

2025-01-14 11:14 UTC, ChunYen-Chen commented on src/configure.py
> +        raise BaseException("Python 3.5 or later is required.")
I think the entire script does not work for Python 3.4 and lower. How about moving this check to the top of the script?

2025-01-15 06:51 UTC, technic960183 commented on doc/wiki/Installation.md
> +   Furthermore, you can override the default setting with the `--machine=` [[option | Installation:-Option-List]] in `configure.py`.
@ChunYen-Chen Is there a section of `--machine` in `Installation:-Option-List`? I'm wondering where will `Installation:-Option-List#--machine` link to?

2025-01-15 08:49 UTC, hyschive commented
@technic960183 Please resolve the conflicts.

2025-01-15 12:11 UTC, technic960183 reviewed
Thanks for the detailed comments.
I have fixed some problems and leave 2 questions (which I have tagged you).
I do not agree with some of the suggestion and have commented the reasons. Please tell me what you think. Thanks.

2025-01-16 09:56 UTC, ChunYen-Chen commented on doc/wiki/Installation.md
> +   Furthermore, you can override the default setting with the `--machine=` [[option | Installation:-Option-List]] in `configure.py`.
> Is there a section of --machine in Installation:-Option-List?

No. Can you add the following code to the `--machine` section? This will add the link to `--machine`.
```markdown
<a name="--machine"></a>
```

2025-01-16 12:16 UTC, technic960183 commented on doc/wiki/Installation-related/Installation:-Option-List.md
> +| `--machine` | Filename string | Select the `*.config` file from the `configs` directory. It will overwrite the default machine set in the default setting file. |
Added.

2025-01-16 12:17 UTC, technic960183 commented on doc/wiki/Installation.md
> +   Furthermore, you can override the default setting with the `--machine=` [[option | Installation:-Option-List]] in `configure.py`.
Added. I put it under `## configure.py Only` to not break the table.

2025-01-16 16:02 UTC, ChunYen-Chen commented on doc/wiki/Installation-related/Installation:-Option-List.md
> +| `--machine` | Filename string | Select the `*.config` file from the `configs` directory. It will overwrite the default machine set in the [[default setting file | Installation#default_setting]]. |
How about this style?
```
| `-h`                                 | -               | Show a short help message. |
| `-lh`                                | -               | Show a detailed help message. |
| `--machine` <a name="--machine"></a> | Filename string | Select the `*.config` file from the `configs` directory. It will overwrite the default machine set in the [[default setting file | Installation#default_setting]]. |
```

2025-01-17 05:51 UTC, technic960183 reviewed
Updated. Thanks for the review and suggestions.

2025-01-17 05:51 UTC, technic960183 commented on src/configure.py
> +    raise BaseException("Python 3.5 or later is required.")
Applied.

2025-01-17 05:51 UTC, technic960183 commented on doc/wiki/Installation-related/Installation:-Option-List.md
> +| `--machine` | Filename string | Select the `*.config` file from the `configs` directory. It will overwrite the default machine set in the [[default setting file | Installation#default_setting]]. |
Applied.

2025-01-17 05:56 UTC, ChunYen-Chen approved these changes

2025-01-20 04:10 UTC, hyschive requested changes
@technic960183 This PR looks great and works well. Thanks for the contribution! I've added some comments before merging. Besides, here is a general question:
- [x] Currently if `src/.local_settings` exists, even if it's empty, we completely ignore `~/.config/gamer/global_settings`. I want to confirm if this behavior is intentional. For example, if both setting files exist, but `machine` is specified only in `global_settings` but not `.local_settings`, should we
    - Adopt the default value `eureka_intel`, as specified in `configure.py`, or
    - Adopt the value set in `global_settings`?

2025-01-20 04:10 UTC, hyschive commented on src/configure.py
> +    3. Fall back to `eureka_intel` for backward compatibility.
IIUC, this routine is general-purpose and can load settings beyond just `machine`. If so, consider revising the description to make it more general.

2025-01-20 04:10 UTC, hyschive commented on src/configure.py
> +    2. Separate the variable name and value with space. The line starts with the variable name.
```suggestion
    2. The line begins with the variable name, followed by one or multiple spaces, and then the value.
```

2025-01-20 04:10 UTC, hyschive commented on src/configure.py
> +    4. Only the last variable of duplicated variables will be loaded.
```suggestion
    4. If a variable is defined multiple times, only the last occurrence will be used.
```

2025-01-20 13:15 UTC, technic960183 reviewed
I have applied the suggestion and fixed the bug.

@hyschive 
It is a bug that if the `.local_settings` is empty, `global_settings` is ignored. I have fixed it and thanks for the catch.
I have also fixed the bug if there are more than one avaiable setting exist. Now each setting will override independently.

@ChunYen-Chen 
I have removed `load_setting()` and put the functionality into the class `SystemSetting`. Please help me to review it. Thanks!

2025-01-21 03:32 UTC, ChunYen-Chen approved these changes
@technic960183 Thanks for the updates and the bug fixes. Please fix the minor style comments. Sorry for not testing the PR fully after the update of the `set_setting.sh`.

2025-01-21 03:32 UTC, ChunYen-Chen commented on src/configure.py
> +
Remove trailing blanks.
```suggestion

```

2025-01-21 03:32 UTC, ChunYen-Chen commented on src/configure.py
> +
Remove trailing blanks.
```suggestion

```

2025-01-21 03:32 UTC, ChunYen-Chen commented on src/configure.py
> +            bool - Whether the file exists.
Remove trailing blanks.
```suggestion
            bool - Whether the file exists.
```

2025-01-21 03:32 UTC, ChunYen-Chen commented on src/configure.py
> +        """Load the system settings from the default setting file. If a setting exists,
[Style]
```suggestion
        """
        Load the system settings from the default setting file. If a setting exists,
```

2025-01-21 07:46 UTC, hyschive approved these changes
@technic960183 Works great! Thanks for the contribution!

2025-01-21 07:46 UTC, merged