[WIP] Updates to cluster merger problem
gamer-project/gamer pull request #48
Opened 2021-01-22 20:12 UTC by jzuhone

This is marked as WIP, but it's actually nearly done. There's just a couple of issues to be dealt with (see below).

* The problem name has been changed to `ClusterMerger` as opposed to `ClusterMerger_vs_Flash`.
* Profile and particle files are now in HDF5 and use the format created by https://github.com/jzuhone/cluster_generator.
* It is now possible to perform a merger with up to 3 clusters.
* Clusters can be added without gas and have DM only (but for now at least one of them needs to have gas).
* Two "color" fields have been added, which are scalar fields for each cluster which can track that particular cluster's gas.
* A metal scalar field can be optionally added to the clusters, where the metal profile is read in from the profile files.
* A new particle attribute for particle types has been added to this test problem, which allows a "star" particle type to be distinguished from a "DM" particle type. For now, there is no other distinction between these particles (the stars are not active, they are not created, they do not explode, etc.). This is simply to distinguish between different spatial distributions of the two different types.
* MHD is now supported. MHD vector potential files can be made with https://github.com/jzuhone/cluster_generator.
* I've added paths for libraries on NASA/Pleiades to the Makefile.

Still need to:

- [ ] Add new files to example directory, fix scripts there
- [ ] Figure out weird issue with second color field, it's not getting the right values

2021-01-25 21:56 UTC, jzuhone commented
@hyschive My only issue with this PR is the passive scalar field `ClusterField2`. In this notebook I create a yt derived field which divides `ClusterField2` by the density:

https://gist.github.com/jzuhone/3db9e7b6337f139e64f7ccbf7d5a7398

It should be 1 everywhere within that circle, like the field for cluster 1, but it's not. It appears that the passive scalar field has been shifted over from the center of that cluster, but I can't find anywhere in my setup that would do that. Any ideas here?

2021-01-28 15:06 UTC, hyschive commented
> @hyschive My only issue with this PR is the passive scalar field `ClusterField2`. In this notebook I create a yt derived field which divides `ClusterField2` by the density:
> 
> https://gist.github.com/jzuhone/3db9e7b6337f139e64f7ccbf7d5a7398
> 
> It should be 1 everywhere within that circle, like the field for cluster 1, but it's not. It appears that the passive scalar field has been shifted over from the center of that cluster, but I can't find anywhere in my setup that would do that. Any ideas here?

@jzuhone I'll look into this issue. Can you send me the complete procedure to generate the `Data_000000` used in your notebook (or a simplified version in case the data size is large)?

2021-01-28 16:52 UTC, jzuhone commented
@hyschive this archive has all of the files you need (`Makefile`, `Input__`, particle and profile files): http://use.yt/upload/4cde74d2

2021-02-01 08:29 UTC, hyschive commented
@jzuhone These [lines](https://github.com/jzuhone/gamer/blob/gcm/src/TestProblem/Hydro/ClusterMerger/Init_TestProb_ClusterMerger.cpp#L541-L544) are incorrect since `ColorField3Idx` will not be set when `Merger_Coll_NumHalos > 2`. It should be something like
```
   if ( Merger_Coll_NumHalos > 2 )
   {  
      if ( r3 < Merger_Coll_ColorRad3 )
         fluid[ColorField3Idx] = Dens;
      else
         fluid[ColorField3Idx] = 0.0;
   }
```

Similar fix should be applied to `ColorField2Idx` too.

2021-02-01 14:00 UTC, jzuhone commented
@hyschive I agree--presumably this doesn't fix it, however, correct?

2021-02-01 14:14 UTC, hyschive commented
> @hyschive I agree--presumably this doesn't fix it, however, correct?

@jzuhone It does fix the issue (at least in my quick test). The results of the original code are nondeterministic and it somehow incorrectly overwrites the `ColorField2Idx` field.

2021-02-01 14:16 UTC, jzuhone commented
@hyschive ok, I'll check. thanks!

2021-02-01 14:57 UTC, hyschive commented
@jzuhone For your reference. Here is the image after fixing this issue.
![Data_000000_Slice_z_cluster2](https://user-images.githubusercontent.com/18057331/106475248-b2ca8200-64e0-11eb-9afe-c3c7e7b1fff3.png)

2021-02-01 15:14 UTC, jzuhone commented
@hyschive You're right! I'm just a bit surprised because I had different logic before and it still wasn't working. I guess that logic was broken also :)

2021-02-01 15:19 UTC, hyschive commented
@jzuhone You are welcome :) Actually I'm surprised too!

2021-02-01 16:06 UTC, jzuhone commented
Ok, @hyschive, this is ready to go unless you have any other changes.

2021-02-17 14:24 UTC, jzuhone commented
Sorry to bug you @hyschive--when you get a chance, if you could have a look at this that would be great.

2021-02-17 14:32 UTC, hyschive commented
> Sorry to bug you @hyschive --when you get a chance, if you could have a look at this that would be great.

@jzuhone No problem at all, and sorry for my slow response on this. I'll look into it early next week.

2021-03-01 10:06 UTC, hyschive requested changes
@jzuhone The PR looks great!
- I have added some minor inline comments.
- The code cannot be compiled when disabling `PARTICLE` or `SUPPORT_HDF5`. This can be easily fixed by enclosing the related code lines within, for example, `#ifdef PARTICLE ... #endif`.
- The input table `Input__Flag_Lohner` is missing.

2021-03-01 20:52 UTC, jzuhone commented on example/test_problem/Hydro/ClusterMerger/yt_script/yt_notebook.ipynb
> +    "slc = yt.SlicePlot(ds, \"z\", [\"El_number_density\", \"kT\", \"magnetic_field_strength\",\n",
I just realized that `El_number_density` is only in yt-4.0. Will fix.

2021-03-01 22:26 UTC, jzuhone commented on src/TestProblem/Hydro/ClusterMerger/Par_Init_ByFunction_ClusterMerger.cpp
> +  H5Sclose(dataspace);
I tried this and it would require messing with double pointers, so I think that this is probably not worth it.

2021-03-03 13:56 UTC, jzuhone commented
Hi @hyschive -- I've implemented all of your suggestions, except the one about putting the particle reading in a loop (just not simple to do--may be worth revisiting, however). I'm just going to run a couple more tests first to make sure everything behaves as expected, but you can review the changes I made in the meantime.

2021-03-03 20:08 UTC, jzuhone commented
@hyschive Ok, I'm satisfied with the results. This is ready to go unless you have something else.

2021-03-05 07:33 UTC, hyschive approved these changes

2021-03-05 07:34 UTC, hyschive commented
@jzuhone Looks good. Thanks for the contribution!

2021-03-05 07:35 UTC, merged